In [1]:
%pip install yfinance --upgrade --no-cache-dir

Requirement already satisfied: yfinance in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (0.2.37)
Collecting yfinance
  Downloading yfinance-0.2.40-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 4.9 MB/s eta 0:00:011
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (4.11.1)
Requirement already satisfied: html5lib>=1.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (1.1)
Requirement already satisfied: pytz>=2022.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (2.4.0)
Requirement already satisfied: requests>=2.31 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: numpy>=1.16.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (1.23.0)
Requirement already satisfied: pandas>=1.3.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (2.2.1)
Requirement already satisfied: peewee>=3.16.2 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (3.17.1)
Requirement already satisfied: multitasking>=0.0.7 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (0.0.11)
Collecting platformdirs>=2.0.0
  Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Requirement already satisfied: lxml>=4.9.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from yfinance) (5.1.0)
Requirement already satisfied: soupsieve>1.2 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.1)
Requirement already satisfied: webencodings in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: six>=1.9 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2024.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests>=2.31->yfinance) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2022.12.7)
Installing collected packages: platformdirs, yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.37
    Uninstalling yfinance-0.2.37:
      Successfully uninstalled yfinance-0.2.37
Successfully installed platformdirs-4.2.2 yfinance-0.2.40
Note: you may need to restart the kernel to use updated packages.

In [1]:
%pip install forex-python

Requirement already satisfied: forex-python in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (1.8)
Requirement already satisfied: requests in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from forex-python) (2.31.0)
Requirement already satisfied: simplejson in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from forex-python) (3.19.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests->forex-python) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests->forex-python) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests->forex-python) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from requests->forex-python) (1.26.15)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import akshare as ak
import pandas as pd
# 单次返回美股所有上市公司的实时行情数据
stock_us_spot_em_df = ak.stock_us_spot_em()
df_stock = stock_us_spot_em_df.sort_values(by='总市值', ascending=False, ignore_index=True)
df_stock
# print(stock_us_spot_em_df)

,序号,名称,最新价,涨跌额,涨跌幅,开盘价,最高价,最低价,昨收价,总市值,市盈率,成交量,成交额,振幅,换手率,代码
0,2229,微软,430.520,1.480,0.34,430.090,432.410,427.130,429.040,3.199756e+12,37.13,18073698.0,7.776429e+09,1.23,0.24,105.MSFT
1,7771,苹果,190.900,-1.450,-0.75,192.265,192.823,190.270,192.350,2.927276e+12,29.16,34648547.0,6.633261e+09,1.33,0.23,105.AAPL
2,8139,FI Enhanced Large Cap Growth ET,868.415,-7.614,-0.87,868.415,868.415,868.415,876.030,2.784510e+12,97.45,183.0,1.589200e+05,0.00,NaN,107.FBGX
3,6792,英伟达,949.500,-4.360,-0.46,954.590,960.200,932.490,953.860,2.335613e+12,54.83,54864799.0,5.188369e+10,2.91,2.23,105.NVDA
4,8095,谷歌-C,178.000,-1.540,-0.86,178.400,178.852,176.780,179.540,2.199724e+12,26.69,16189404.0,2.876609e+09,1.15,0.25,105.GOOG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11517,11515,Holley Inc Wt,0.120,-0.071,-37.27,0.160,0.164,0.116,0.191,NaN,NaN,62529.0,8.044000e+03,25.09,NaN,106.HLLY_WS
11518,11516,Oak Woods Acquisition Corp Rt,0.171,-0.119,-41.03,0.172,0.183,0.171,0.290,NaN,NaN,1011.0,1.790000e+02,4.28,NaN,105.OAKUR
11519,11517,Maris-Tech Ltd Wt,0.056,-0.044,-44.20,0.056,0.056,0.056,0.100,NaN,NaN,320.0,1.700000e+01,0.00,NaN,105.MTEKW
11520,11518,Coeptis Therapeutics Holdings I,0.022,-0.018,-44.47,0.021,0.022,0.021,0.040,NaN,NaN,12579.0,2.670000e+02,3.02,NaN,105.COEPW
11521,11521,International Media Acquisition,0.015,-0.014,-48.98,0.021,0.021,0.015,0.029,NaN,NaN,3500.0,6.700000e+01,21.77,NaN,105.IMAQW

In [8]:
# df_stock = stock_us_spot_em_df.sort_values(by='总市值', ascending=False, ignore_index=True)
# df_stock

,序号,名称,最新价,涨跌额,涨跌幅,开盘价,最高价,最低价,昨收价,总市值,市盈率,成交量,成交额,振幅,换手率,代码
0,806,微软,415.28,10.76,2.66,407.62,415.57,406.79,404.52,3.085712e+12,37.38,22457003.0,9.284345e+09,2.17,0.30,105.MSFT
1,4338,苹果,173.23,0.48,0.28,173.15,174.03,171.01,172.75,2.674997e+12,26.51,59825372.0,1.034060e+10,1.75,0.39,105.AAPL
2,622,FI Enhanced Large Cap Growth ET,833.15,26.80,3.32,833.15,833.15,833.15,806.35,2.673457e+12,92.10,103.0,8.581400e+04,0.00,NaN,107.FBGX
3,271,英伟达,919.13,61.39,7.16,880.49,919.60,861.50,857.74,2.297825e+12,77.21,66807515.0,5.992780e+10,6.77,2.67,105.NVDA
4,1103,亚马逊,175.39,3.43,1.99,173.50,176.76,171.98,171.96,1.821843e+12,59.88,36610604.0,6.418865e+09,2.78,0.35,105.AMZN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11614,11612,Estrella Immunopharma Inc Wt,0.03,-0.03,-50.00,0.03,0.03,0.03,0.06,NaN,NaN,943.0,2.900000e+01,0.00,NaN,105.ESLAW
11615,11613,Bannix Acquisition Corp Wt,0.01,-0.01,-50.00,0.01,0.01,0.01,0.02,NaN,NaN,29050.0,2.050000e+02,0.00,NaN,105.BNIXW
11616,11614,Alliance Entertainment Holding,0.01,-0.01,-50.00,0.03,0.03,0.01,0.02,NaN,NaN,3000.0,6.900000e+01,100.00,NaN,105.AENTW
11617,11615,Bannix Acquisition Corp Rt,0.10,-0.11,-52.38,0.10,0.10,0.10,0.21,NaN,NaN,10098.0,9.970000e+02,0.00,NaN,105.BNIXR
11618,11617,Blade Air Mobility Inc Wt,0.12,-0.23,-65.71,0.30,0.30,0.12,0.35,NaN,NaN,339085.0,4.940600e+04,51.43,NaN,105.BLDEW

In [38]:
# df_stock.loc[2, '名称']

'FI Enhanced Large Cap Growth ET'

In [2]:
us_stock_name_df = ak.get_us_stock_name()
us_stock_name_df

KeyboardInterrupt:

In [4]:
# 将 DataFrame 保存到 CSV 文件
us_stock_name_df.to_csv('us_stock_name.csv', index=False)  # index=False 表示不将行索引写入 CSV 文件

In [4]:
stock_dir = './data/us_stock_name.csv'
us_stock_name_df =pd.read_csv(stock_dir)
us_stock_name_df

                                  name                            cname symbol
0                      Microsoft Corp.                             微软公司   MSFT
1                          Apple, Inc.                             苹果公司   AAPL
2                         NVIDIA Corp.                            英伟达公司   NVDA
3                     Amazon.com, Inc.                            亚马逊公司   AMZN
4                       Alphabet, Inc.                               谷歌   GOOG
...                                ...                              ...    ...
10732                             ZTST                             ZTST   ZTST
10733  F/M 2-YEAR INVESTMENT GRADE COR  F/M 2-YEAR INVESTMENT GRADE COR   ZTWO
10734                    Zura Bio Ltd.                    Zura Bio Ltd.  ZURAW
10735       ZyVersa Therapeutics, Inc.       ZyVersa Therapeutics, Inc.  ZVSAW
10736                  IEX Test symbol                  IEX Test symbol  ZXIET

[10737 rows x 3 columns]

In [5]:
# 找出包含"ETF"或"ETN"的行
ETF_ETN_rows = us_stock_name_df[us_stock_name_df['cname'].str.contains('ETF|ETN', case=False)]
ETF_ETN_rows

Empty DataFrame
Columns: [name, cname, symbol]
Index: []

In [6]:
ETF_ETN_rows.loc[1000:1500, :]

Empty DataFrame
Columns: [name, cname, symbol]
Index: []

In [35]:
# 删除包含"ETF"或"ETN"的行
df_stock_name = us_stock_name_df[~us_stock_name_df['cname'].str.contains('ETF|ETN', case=False)]
df_stock_name = df_stock_name.reset_index(drop=True)
df_stock_name

                                  name                            cname symbol
0                      Microsoft Corp.                             微软公司   MSFT
1                          Apple, Inc.                             苹果公司   AAPL
2                         NVIDIA Corp.                            英伟达公司   NVDA
3                     Amazon.com, Inc.                            亚马逊公司   AMZN
4                       Alphabet, Inc.                               谷歌   GOOG
...                                ...                              ...    ...
10732                             ZTST                             ZTST   ZTST
10733  F/M 2-YEAR INVESTMENT GRADE COR  F/M 2-YEAR INVESTMENT GRADE COR   ZTWO
10734                    Zura Bio Ltd.                    Zura Bio Ltd.  ZURAW
10735       ZyVersa Therapeutics, Inc.       ZyVersa Therapeutics, Inc.  ZVSAW
10736                  IEX Test symbol                  IEX Test symbol  ZXIET

[10737 rows x 3 columns]

In [36]:
# 将 DataFrame 保存到 CSV 文件
df_stock_name.to_csv('us_stock_name.csv', index=False)  # index=False 表示不将行索引写入 CSV 文件

In [7]:
df_stock_name.loc[50:100, :]

NameError: name 'df_stock_name' is not defined

In [8]:
df_dup = us_stock_name_df['symbol'].duplicated()
df_dup = list(df_dup)
has_true = any(df_dup)
print(has_true)

False

In [9]:
df_name = list(us_stock_name_df['symbol'])
df_name

['MSFT',
 'AAPL',
 'NVDA',
 'AMZN',
 'GOOG',
 'GOOGL',
 'META',
 'BRK.A',
 'BRK.B',
 'TSM',
 'LLY',
 'AVGO',
 'NVO',
 'TSLA',
 'JPM',
 'V',
 'WMT',
 'UNH',
 'MA',
 'XOM',
 'JNJ',
 'PG',
 'ASML',
 'HD',
 'AMD',
 'TM',
 'ABBV',
 'COST',
 'ORCL',
 'MRK',
 'CRM',
 'BAC',
 'CVX',
 'NFLX',
 'KO',
 'ADBE',
 'ACN',
 'TMO',
 'PEP',
 'LIN',
 'SAP',
 'MCD',
 'AZN',
 'ABT',
 'SHEL',
 'NVS',
 'DIS',
 'WFC',
 'CSCO',
 'TMUS',
 'RDS.A',
 'QCOM',
 'BABA',
 'INTC',
 'DHR',
 'INTU',
 'GE',
 'IBM',
 'CMCSA',
 'VZ',
 'AMAT',
 'CAT',
 'KOF',
 'UBER',
 'PFE',
 'AXP',
 'TXN',
 'TTE',
 'NOW',
 'NKE',
 'UNP',
 'PDD',
 'AMGN',
 'PM',
 'BHP',
 'MS',
 'HDB',
 'RY',
 'HSBC',
 'LOW',
 'COP',
 'SYK',
 'ISRG',
 'SPGI',
 'UPS',
 'HON',
 'ARM',
 'BUD',
 'TOT',
 'GS',
 'MUFG',
 'PLD',
 'T',
 'UL',
 'BLK',
 'SNY',
 'SCHW',
 'LRCX',
 'RTX',
 'BKNG',
 'NEE',
 'ELV',
 'BA',
 'ETN',
 'ANTM',
 'PGR',
 'MDT',
 'TJX',
 'BMY',
 'C',
 'TD',
 'STLA',
 'VRTX',
 'SONY',
 'REGN',
 'ABNB',
 'LMT',
 'DE',
 'MU',
 'SBUX',
 'CB',
 'BP',
 'MMC',
 'RIO',
 'ADP',
 'CI',
 'UBS',
 'ADI',
 'MDLZ',
 'BSX',
 'SHOP',
 'AMT',
 'CVS',
 'DCM',
 'PBR',
 'GILD',
 'KLAC',
 'PANW',
 'IBN',
 'BX',
 'STO',
 'GSK',
 'SHW',
 'SNPS',
 'KKR',
 'HCA',
 'ANET',
 'EQIX',
 'WM',
 'ZTS',
 'DEO',
 'CP',
 'CDNS',
 'CNI',
 'DELL',
 'RELX',
 'INFY',
 'SMFG',
 'MELI',
 'ICE',
 'ITW',
 'CME',
 'EQNR',
 'TGT',
 'CNQ',
 'CRWD',
 'ENB',
 'SO',
 'MO',
 'GD',
 'CSX',
 'RACE',
 'UTX',
 'DUK',
 'SLB',
 'CMG',
 'CL',
 'MAR',
 'TRI',
 'FISV',
 'WDAY',
 'MCO',
 'EOG',
 'NTES',
 'MCK',
 'BDX',
 'ABB',
 'BN',
 'NOC',
 'PH',
 'BMO',
 'SAN',
 'USB',
 'BTI',
 'ITUB',
 'SCCO',
 'APH',
 'MPC',
 'NXPI',
 'PYPL',
 'TT',
 'ORLY',
 'TDG',
 'PSX',
 'ECL',
 'BBVA',
 'CTAS',
 'FDX',
 'AON',
 'EMR',
 'MRVL',
 'APO',
 'COIN',
 'MNST',
 'EPD',
 'BNS',
 'PNC',
 'SMCI',
 'PCAR',
 'ROP',
 'AMX',
 'DVMT',
 'NSC',
 'FCX',
 'RSG',
 'LULU',
 'PXD',
 'CRH',
 'MSI',
 'PLTR',
 'HMC',
 'ADSK',
 'EL',
 'VALE',
 'APD',
 'NU',
 'AJG',
 'EW',
 'FTNT',
 'OXY',
 'SNOW',
 'CEG',
 'AZO',
 'WELL',
 'COF',
 'ING',
 'CPRT',
 'DASH',
 'MMM',
 'MET',
 'MFG',
 'HLT',
 'CARR',
 'E',
 'DXCM',
 'PSA',
 'NGG',
 'AIG',
 'DHI',
 'ET',
 'SPOT',
 'SQ',
 'TRV',
 'VLO',
 'TFC',
 'ROST',
 'MCHP',
 'SPG',
 'CCI',
 'F',
 'AFL',
 'STZ',
 'GWW',
 'ODFL',
 'IQV',
 'FWONK',
 'CM',
 'SRE',
 'LEN',
 'TAK',
 'O',
 'GM',
 'IDXX',
 'DLR',
 'IBKR',
 'HES',
 'OKE',
 'SU',
 'URI',
 'MSCI',
 'WMB',
 'NUE',
 'AEP',
 'PAYX',
 'FMX',
 'TEL',
 'ALC',
 'CHTR',
 'WCN',
 'A',
 'MFC',
 'PCG',
 'STM',
 'MRNA',
 'KMB',
 'BSBR',
 'FAST',
 'KHC',
 'GEHC',
 'TRP',
 'ALL',
 'VXZB',
 'BK',
 'HUM',
 'FWONA',
 'AME',
 'CNC',
 'JCI',
 'BBT',
 'LEN.B',
 'AMP',
 'MPLX',
 'JD',
 'LHX',
 'KDP',
 'NEM',
 'HSY',
 'DOW',
 'FERG',
 'FIS',
 'ABEV',
 'PBR.A',
 'PRU',
 'LYG',
 'D',
 'KMI',
 'SYY',
 'LVS',
 'KR',
 'HLN',
 'YUM',
 'OTIS',
 'LI',
 'FLUT',
 'CTVA',
 'KVUE',
 'CMI',
 'CTSH',
 'GIS',
 'EXC',
 'MLM',
 'LNG',
 'VEEV',
 'EA',
 'IT',
 'ABC',
 'IR',
 'CSGP',
 'BIDU',
 'IMO',
 'VMC',
 'MPWR',
 'DG',
 'ON',
 'PWR',
 'BCS',
 'NDAQ',
 'FI',
 'VRSK',
 'ACGL',
 'WIT',
 'PPG',
 'BIIB',
 'GPN',
 'CVE',
 'CDW',
 'BCE',
 'CPNG',
 'SE',
 'FANG',
 'CCEP',
 'RCL',
 'NET',
 'LYB',
 'ROK',
 'HAL',
 'EFX',
 'DLTR',
 'PEG',
 'RYAAY',
 'SLF',
 'FICO',
 'EXR',
 'ED',
 'BKR',
 'HUBS',
 'VICI',
 'ORAN',
 'DFS',
 'XYL',
 'HPQ',
 'DD',
 'ZS',
 'BBD',
 'CHT',
 'FTV',
 'DVN',
 'GFS',
 'XEL',
 'ADM',
 'HIG',
 'ANSS',
 'WLTW',
 'NWG',
 'DB',
 'CBRE',
 'PUK',
 'CAH',
 'GLW',
 'GRMN',
 'TCOM',
 'RMD',
 'MTD',
 'WTW',
 'GOLD',
 'AEM',
 'DAL',
 'ICLR',
 'GIB',
 'TSCO',
 'BBDO',
 'EBAY',
 'EIX',
 'HWM',
 'ULTA',
 'KEYS',
 'BF.A',
 'RBLX',
 'SPLK',
 'NTR',
 'TROW',
 'LLYVK',
 'ZBH',
 'AVB',
 'WST',
 'SYM',
 'BF.B',
 'WEC',
 'ARES',
 'VRT',
 'WY',
 'TU',
 'GEHCV',
 'HEI',
 'CHD',
 'MSTR',
 'QSR',
 'PKX',
 'FITB',
 'WAB',
 'TTWO',
 'OWL',
 'RJF',
 'TLK',
 'VOD',
 'RKT',
 'IX',
 'TEF',
 'NVR',
 'BRO',
 'SBAC',
 'ASX',
 'FCAU',
 'DOV',
 'EQR',
 'BR',
 'MTB',
 'CQP',
 'IRM',
 'RCI',
 'PHM',
 'BLDR',
 'MOH',
 'HPE',
 'AWK',
 'AXON',
 'DTE',
 'TRGP',
 'PINS',
 'DECK',
 'ALGN',
 'STE',
 'LYV',
 'CCUR',
 'BHGE',
 'CCE',
 'MBLY',
 'HRS',
 'DPS',
 'PTC',
 'BLL',
 'TS',
 'ARE',
 'STT',
 'FE',
 'ROL',
 'ILMN',
 'BAX',
 'ETR',
 'TW',
 'APTV',
 'VLTO',
 'FCNCA',
 'FNV',
 'WRB',
 'EBR.B',
 'Q',
 'EC',
 'TECK',
 'INVH',
 'ZM',
 'MT',
 'GPC',
 'NTAP',
 'ES',
 'LB',
 'FLT',
 'ERIE',
 'ENTG',
 'WAT',
 'GMAB',
 'BALL',
 'HUBB',
 'BT',
 'JBHT',
 'IOT',
 'IFF',
 'STLD',
 'APP',
 'DRI',
 'UMC',
 'HEI.A',
 'CCL',
 'WPM',
 'KYO',
 'WDC',
 'VST',
 'COO',
 'LUV',
 'TDY',
 'PPL',
 'NOK',
 'KSPI',
 'CTRA',
 'KB',
 'CELH',
 'TSN',
 'LSXMA',
 'DKNG',
 'MKL',
 'LSXMK',
 'LPLA',
 'LSXMB',
 'FTS',
 'PBA',
 'AEE',
 'HBAN',
 'SNAP',
 'VRSN',
 'EBR',
 'CBOE',
 'PHG',
 'CLX',
 'STX',
 'CHKP',
 'HCN',
 'PFG',
 'JBL',
 'ALNY',
 'BAH',
 'MKC.V',
 'MKC',
 'HRL',
 'OMC',
 'RBS',
 'EXPE',
 'CUK',
 'J',
 'WBA',
 'ERIC',
 'K',
 'CINF',
 'LH',
 'WPPGY',
 'RS',
 'WLK',
 'FDS',
 'TYL',
 'NMR',
 'IEX',
 'FITBI',
 'CNP',
 'RF',
 'RPRX',
 'SHG',
 'VTR',
 'HOLX',
 'JHX',
 'CMS',
 'TME',
 'CCJ',
 'TXT',
 'ATO',
 'EPAM',
 'WMG',
 'CCC',
 'ENPH',
 'IHG',
 'AVY',
 'EXPD',
 'FSLR',
 'SYF',
 'LDOS',
 'EDR',
 'SWKS',
 'VIV',
 'BGNE',
 'CE',
 'AVTR',
 'PSTG',
 'CSL',
 'CG',
 'L',
 'PKG',
 'NTRS',
 'AKAM',
 'PPD',
 'YUMC',
 'SUI',
 'MAS',
 'AER',
 'EG',
 'LII',
 'BBY',
 'BAM',
 'BEKE',
 'ZTO',
 'GDDY',
 'TER',
 'CEGVV',
 'BMRN',
 'RTO',
 'SIRI',
 'CF',
 'H',
 'ABX',
 'CVNA',
 'MAA',
 'MANH',
 'CFG',
 'NWS',
 'CNHI',
 'ESS',
 'WSO',
 'SUZ',
 'GGG',
 'MGA',
 'SSNC',
 'TRU',
 'DPZ',
 'TRMB',
 'WSO.B',
 'POOL',
 'SNA',
 'AEG',
 'SAIA',
 'CRBG',
 'RE',
 'EQT',
 'WSM',
 'RPM',
 'NWSA',
 'NICE',
 'NDSN',
 'TEVA',
 'BEN',
 'EME',
 'LW',
 'DKS',
 'EDU',
 'HOOD',
 'HST',
 'SYMC',
 'ALB',
 'BSY',
 'PKI',
 'MRO',
 'NLOK',
 'ZBRA',
 'LECO',
 'DGX',
 'ACGLO',
 'VTRS',
 'FOXA',
 'XPO',
 'LOGI',
 'SWK',
 'GFI',
 'UAL',
 'PARAA',
 'RYAN',
 'TAP',
 'SQM',
 'TKO',
 'FNF',
 'KEY',
 'XP',
 'BIP',
 'BURL',
 'RBA',
 'LKQ',
 'NBIX',
 'BAP',
 'AGR',
 'AMCR',
 'DT',
 'INCY',
 'OVV',
 'PATH',
 'CAG',
 'MGM',
 'BG',
 'OC',
 'CRL',
 'TOST',
 'RVTY',
 'PNR',
 'AMH',
 'TAP.A',
 'Z',
 'MORN',
 'KIM',
 'AZPN',
 'GFL',
 'WES',
 'FOX',
 'SJM',
 'ZG',
 'FND',
 'RDY',
 'USFD',
 'UHAL',
 'CPB',
 'KMX',
 'WPC',
 'BLD',
 'LNT',
 'NIO',
 'IP',
 'PODD',
 'JKHY',
 'BRKR',
 'UHAL.B',
 'GLPI',
 'NRG',
 'AOS',
 'TFII',
 'IPG',
 'ARCC',
 'UDR',
 'WMS',
 'VNTV',
 'WBDWV',
 'GRAB',
 'ELS',
 'TOL',
 'DISCB',
 'ACM',
 'DISCA',
 'MEDP',
 'UGIC',
 'RIVN',
 'RNR',
 'LUX',
 'SNN',
 'VFS',
 'KRTX',
 'FLEX',
 'NI',
 'CTL',
 'RGA',
 'ACI',
 'JNPR',
 'CX',
 'LAMR',
 'DVA',
 'TPL',
 'WRK',
 'LEGN',
 'CNA',
 'KEP',
 'EVRG',
 'DOCU',
 'TECH',
 'QVCA',
 'FMS',
 'UTHR',
 'BCH',
 'PFGC',
 'PAA',
 'AES',
 'GL',
 'WYNN',
 'PCOR',
 'UHS',
 'HTHT',
 'ALLE',
 'JEC',
 'REG',
 'HII',
 'AFRM',
 'DEC',
 'SRPT',
 'RL',
 'RRX',
 'REXR',
 'ALLY',
 'FFIV',
 'COTY',
 'QRVO',
 'SRAD',
 'NVT',
 'TWLO',
 'FIVE',
 'DINO',
 'WTR',
 'EQH',
 'DIDI',
 'AAXN',
 'CASY',
 'EXAS',
 'LSCC',
 'FVD',
 'SCI',
 'CHK',
 'UWMC',
 'CDAY',
 'AFG',
 'WYN',
 'DOX',
 'RGEN',
 'ELF',
 'EMN',
 'TPR',
 'SBS',
 'ONON',
 'CPT',
 'EWBC',
 'TFX',
 'PAYC',
 'DAY',
 'FIX',
 'X',
 'MNDY',
 'ESTC',
 'U',
 'ITT',
 'OTEX',
 'ENIA',
 'CTLT',
 'FBIN',
 'CUBE',
 'BBWI',
 'CLF',
 'PAG',
 'TREX',
 'AABA',
 'MOS',
 'QGEN',
 'CLH',
 'BXP',
 'TXRH',
 'NLY',
 'BJ',
 'CFLT',
 'CREE',
 'WTRG',
 'BIO',
 'ALV',
 'TTEK',
 'CHE',
 'WPP',
 'THC',
 'FTI',
 'UNM',
 'SWAV',
 'HSIC',
 'AU',
 'DOC',
 'WEX',
 'TMK',
 'AAL',
 'GWRE',
 'STN',
 'DUOL',
 'PCTY',
 'XPEV',
 'BIO.B',
 'CCK',
 'BEPC',
 'ATR',
 'APG',
 'INFA',
 'APA',
 'TPX',
 'UHALB',
 'PEAK',
 'PEN',
 'COHR',
 'GLOB',
 'BWXT',
 'SNX',
 'PR',
 'AIZ',
 'TTC',
 'SKX',
 'CZR',
 'BSAC',
 'CART',
 'JEF',
 'ESLT',
 'KNX',
 'VIPS',
 'SLW',
 'BPYPP',
 'SEIC',
 'CW',
 'CNM',
 'LNW',
 'WWD',
 'TIMB',
 'BIRK',
 'PNW',
 'GTLB',
 'COG',
 'JLL',
 'ONTO',
 'AGNCN',
 'PSO',
 'ASR',
 'AGNCM',
 'CHRW',
 'WSC',
 'IMGN',
 'SSD',
 'EXP',
 'EGP',
 'DCI',
 'HLI',
 'MYL',
 'PRI',
 'AGCO',
 'MKSI',
 'ASND',
 'MTN',
 'FRT',
 'SKM',
 'PSN',
 'LBRDK',
 'HNP',
 'MKTX',
 'MUSA',
 'NCLH',
 'LBRDA',
 'RHI',
 'ROIV',
 'WF',
 'WBS',
 'GPK',
 'WWE',
 'AGNCP',
 'ARMK',
 'GNTX',
 'CHDN',
 'FUTU',
 'CACI',
 'BRKS',
 'MIDD',
 'FHN',
 'KBR',
 'AMKR',
 'NXT',
 'SBGL',
 'VRX',
 'AS',
 'ORI',
 'SITE',
 'LUK',
 'DBX',
 'WFRD',
 ...]

In [10]:
us_stock_name_df.head(20)

                                            name                 cname symbol
0                                Microsoft Corp.                  微软公司   MSFT
1                                    Apple, Inc.                  苹果公司   AAPL
2                                   NVIDIA Corp.                 英伟达公司   NVDA
3                               Amazon.com, Inc.                 亚马逊公司   AMZN
4                                 Alphabet, Inc.                    谷歌   GOOG
5                                 Alphabet, Inc.                 谷歌A类股  GOOGL
6                           Meta Platforms, Inc.  Meta Platforms, Inc.   META
7                       Berkshire Hathaway, Inc.              伯克希尔-哈撒韦  BRK.A
8                       Berkshire Hathaway, Inc.             伯克希尔-哈撒韦B  BRK.B
9   Taiwan Semiconductor Manufacturing Co., Ltd.            台湾积体电路制造公司    TSM
10                               Eli Lilly & Co.                  礼来公司    LLY
11                                 Broadcom Inc.                    博通   AVGO
12                              Novo Nordisk A/S                诺和诺德公司    NVO
13                                   Tesla, Inc.                   特斯拉   TSLA
14                          JPMorgan Chase & Co.                摩根大通公司    JPM
15                                    Visa, Inc.                 维萨卡公司      V
16                                 Walmart, Inc.                 沃尔玛公司    WMT
17                      UnitedHealth Group, Inc.              美国联合健康集团    UNH
18                              Mastercard, Inc.                万事达卡公司     MA
19                             Exxon Mobil Corp.               埃克森美孚公司    XOM

In [11]:
import yfinance as yf

msft = yf.Ticker("MSFT")

# get all stock info
data = msft.info
data

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 221000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 56,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 9276400,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 64,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'totalPay': 3591277,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 51,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 3452196,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 49,
   'title': 'Executive VP & Chief Commercial Officer',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'totalPay': 3355797,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 51,
   'title': 'Executive Vice President of Business Development, Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 2460507,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 56,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 51,
   'title': 'Executive VP of AI & CTO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brett  Iversen',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hossein  Nowbar',
   'title': 'Chief Legal Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Chief Communications Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 3,
 'boardRisk': 5,
 'compensationRisk': 2,
 'shareHolderRightsRisk': 2,
 'overallRisk': 1,
 'governanceEpochDate': 1714521600,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 429.04,
 'open': 430.09,
 'dayLow': 427.13,
 'dayHigh': 432.41,
 'regularMarketPreviousClose': 429.04,
 'regularMarketOpen': 430.09,
 'regularMarketDayLow': 427.13,
 'regularMarketDayHigh': 432.41,
 'dividendRate': 3.0,
 'dividendYield': 0.0069999998,
 'exDividendDate': 1715731200,
 'payoutRatio': 0.24780001,
 'fiveYearAvgDividendYield': 0.94,
 'beta': 0.893,
 'trailingPE': 37.30676,
 'forwardPE': 32.46757,
 'volume': 17955182,
 'regularMarketVolume': 17955182,
 'averageVolume': 19682624,
 'averageVolume10days': 16951000,
 'averageDailyVolume10Day': 16951000,
 'bid': 430.37,
 'ask': 451.52,
 'bidSize': 100,
 'askSize': 100,
 'marketCap': 3199757975552,
 'fiftyTwoWeekLow': 309.45,
 'fiftyTwoWeekHigh': 432.97,
 'priceToSalesTrailing12Months': 13.524829,
 'fiftyDayAverage': 415.933,
 'twoHundredDayAverage': 375.92285,
 'trailingAnnualDividendRate': 2.93,
 'trailingAnnualDividendYield': 0.0068292003,
 'currency': 'USD',
 'enterpriseValue': 3225972375552,
 'profitMargins': 0.36426997,
 'floatShares': 7421528951,
 'sharesOutstanding': 7432309760,
 'sharesShort': 49773013,
 'sharesShortPriorMonth': 55771473,
 'sharesShortPreviousMonthDate': 1711584000,
 'dateShortInterest': 1714435200,
 'sharesPercentSharesOut': 0.0067000003,
 'heldPercentInsiders': 0.00054000004,
 'heldPercentInstitutions': 0.73643,
 'shortRatio': 2.48,
 'shortPercentOfFloat': 0.0067000003,
 'impliedSharesOutstanding': 7432309760,
 'bookValue': 34.058,
 'priceToBook': 12.640789,
 'lastFiscalYearEnd': 1688083200,
 'nextFiscalYearEnd': 1719705600,
 'mostRecentQuarter': 1711843200,
 'earningsQuarterlyGrowth': 0.199,
 'netIncomeToCommon': 86181003264,
 'trailingEps': 11.54,
 'forwardEps': 13.26,
 'pegRatio': 2.24,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 13.636,
 'enterpriseToEbitda': 25.77,
 '52WeekChange': 0.32093763,
 'SandP52WeekChange': 0.27840328,
 'lastDividendValue': 0.75,
 'lastDividendDate': 1715731200,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 430.52,
 'targetHighPrice': 600.0,
 'targetLowPrice': 397.92,
 'targetMeanPrice': 481.74,
 'targetMedianPrice': 477.33,
 'recommendationMean': 1.7,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 47,
 'totalCash': 80013000704,
 'totalCashPerShare': 10.766,
 'ebitda': 125182001152,
 'totalDebt': 106228998144,
 'quickRatio': 1.132,
 'currentRatio': 1.242,
 'totalRevenue': 236583993344,
 'debtToEquity': 41.963,
 'revenuePerShare': 31.834,
 'returnOnAssets': 0.15295,
 'returnOnEquity': 0.38487998,
 'freeCashflow': 61497999360,
 'operatingCashflow': 110122999808,
 'earningsGrowth': 0.2,
 'revenueGrowth': 0.17,
 'grossMargins': 0.69894,
 'ebitdaMargins': 0.52911997,
 'operatingMargins': 0.44588003,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.1306}

In [12]:
data['earningsReport']

KeyError: 'earningsReport'

In [3]:
# financials = msft.financials
# financials

,2023-06-30,2022-06-30,2021-06-30,2020-06-30
Tax Effect Of Unusual Items,-2850000.0,43420000.0,180160797.164637,4760000.0
Tax Rate For Calcs,0.19,0.13,0.138266,0.17
Normalized EBITDA,105155000000.0,99905000000.0,83831000000.0,68395000000.0
Total Unusual Items,-15000000.0,334000000.0,1303000000.0,28000000.0
Total Unusual Items Excluding Goodwill,-15000000.0,334000000.0,1303000000.0,28000000.0
Net Income From Continuing Operation Net Minority Interest,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Reconciled Depreciation,13861000000.0,14460000000.0,11686000000.0,12796000000.0
Reconciled Cost Of Revenue,65863000000.0,62650000000.0,52232000000.0,46078000000.0
EBITDA,105140000000.0,100239000000.0,85134000000.0,68423000000.0
EBIT,91279000000.0,85779000000.0,73448000000.0,55627000000.0
Net Interest Income,1026000000.0,31000000.0,-215000000.0,89000000.0
Interest Expense,1968000000.0,2063000000.0,2346000000.0,2591000000.0
Interest Income,2994000000.0,2094000000.0,2131000000.0,2680000000.0
Normalized Income,72373150000.0,72447420000.0,60148160797.164635,44257760000.0
Net Income From Continuing And Discontinued Operation,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Total Expenses,123392000000.0,114887000000.0,98172000000.0,90056000000.0
Total Operating Income As Reported,88523000000.0,83383000000.0,69916000000.0,52959000000.0
Diluted Average Shares,7472000000.0,7540000000.0,7608000000.0,7683000000.0
Basic Average Shares,7446000000.0,7496000000.0,7547000000.0,7610000000.0
Diluted EPS,9.68,9.65,8.05,5.76
Basic EPS,9.72,9.7,8.12,5.82
Diluted NI Availto Com Stockholders,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income Common Stockholders,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income Including Noncontrolling Interests,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Net Income Continuous Operations,72361000000.0,72738000000.0,61271000000.0,44281000000.0
Tax Provision,16950000000.0,10978000000.0,9831000000.0,8755000000.0
Pretax Income,89311000000.0,83716000000.0,71102000000.0,53036000000.0
Other Income Expense,-238000000.0,302000000.0,1401000000.0,-12000000.0
Other Non Operating Income Expenses,-223000000.0,-32000000.0,98000000.0,-40000000.0
Special Income Charges,-30000000.0,-101000000.0,-13000000.0,-133000000.0
Write Off,30000000.0,101000000.0,13000000.0,133000000.0
Gain On Sale Of Security,15000000.0,435000000.0,1316000000.0,161000000.0
Net Non Operating Interest Income Expense,1026000000.0,31000000.0,-215000000.0,89000000.0
Interest Expense Non Operating,1968000000.0,2063000000.0,2346000000.0,2591000000.0
Interest Income Non Operating,2994000000.0,2094000000.0,2131000000.0,2680000000.0
Operating Income,88523000000.0,83383000000.0,69916000000.0,52959000000.0
Operating Expense,57529000000.0,52237000000.0,45940000000.0,43978000000.0
Research And Development,27195000000.0,24512000000.0,20716000000.0,19269000000.0
Selling General And Administration,30334000000.0,27725000000.0,25224000000.0,24709000000.0
Selling And Marketing Expense,22759000000.0,21825000000.0,20117000000.0,19598000000.0
General And Administrative Expense,7575000000.0,5900000000.0,5107000000.0,5111000000.0
Other Gand A,7575000000.0,5900000000.0,5107000000.0,5111000000.0
Gross Profit,146052000000.0,135620000000.0,115856000000.0,96937000000.0
Cost Of Revenue,65863000000.0,62650000000.0,52232000000.0,46078000000.0
Total Revenue,211915000000.0,198270000000.0,168088000000.0,143015000000.0
Operating Revenue,211915000000.0,198270000000.0,168088000000.0,143015000000.0

In [14]:
# symbol = df_name[0]
# print(symbol)
# appl = yf.Ticker(symbol)
# appl.info

MSFT

In [16]:
# symbol = df_name[9]
symbol = 'AAPL'
print(symbol)
cmpy = yf.Ticker(symbol)
# cmpy_income = cmpy.income_stmt
cmpy_income = cmpy.quarterly_income_stmt
# cmpy_income = cmpy.get_income_stmt(freq='quarterly')

cmpy_income = cmpy_income.T
# 检查是否存在 'Research And Development' 列，如果不存在，则创建一个值为 0 的新列
# if 'Research And Development' not in cmpy_income.columns:
#     cmpy_income['Research And Development'] = 0

cmpy_income
# cmpy.info

AAPL

,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,Net Interest Income,Interest Expense,...,Interest Expense Non Operating,Interest Income Non Operating,Operating Income,Operating Expense,Research And Development,Selling General And Administration,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue
2024-03-31,0.0,0.158,30736000000.0,23636000000.0,2836000000.0,48482000000.0,30736000000.0,27900000000.0,NaN,NaN,...,NaN,NaN,27900000000.0,14371000000.0,7903000000.0,6468000000.0,42271000000.0,48482000000.0,90753000000.0,90753000000.0
2023-12-31,0.0,0.159,43221000000.0,33916000000.0,2848000000.0,64720000000.0,43221000000.0,40373000000.0,NaN,NaN,...,NaN,NaN,40373000000.0,14482000000.0,7696000000.0,6786000000.0,54855000000.0,64720000000.0,119575000000.0,119575000000.0
2023-09-30,0.0,0.149715,30653000000.0,22956000000.0,2653000000.0,49071000000.0,30653000000.0,28000000000.0,-18000000.0,1002000000.0,...,1002000000.0,984000000.0,26969000000.0,13458000000.0,7307000000.0,6151000000.0,40427000000.0,49071000000.0,89498000000.0,89498000000.0
2023-06-30,0.0,0.125,26783000000.0,19881000000.0,3052000000.0,45384000000.0,26783000000.0,23731000000.0,-18000000.0,998000000.0,...,998000000.0,980000000.0,22998000000.0,13415000000.0,7442000000.0,5973000000.0,36413000000.0,45384000000.0,81797000000.0,81797000000.0
2023-03-31,0.0,0.149,31216000000.0,24160000000.0,2898000000.0,52860000000.0,31216000000.0,28318000000.0,-12000000.0,930000000.0,...,930000000.0,918000000.0,28318000000.0,13658000000.0,7457000000.0,6201000000.0,41976000000.0,52860000000.0,94836000000.0,94836000000.0
2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-135000000.0,1003000000.0,...,1003000000.0,868000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-74000000.0,827000000.0,...,827000000.0,753000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
latest_quarter = cmpy_income.index.max()
latest_quarter

Timestamp('2024-03-31 00:00:00')

In [18]:
cmpy_income.loc[latest_quarter, "Operating Revenue"]

90753000000.0

In [19]:
df_info = cmpy.info
df_info['financialCurrency']
# financialCurrency

'USD'

In [ ]:
# ['Operating Revenue', 'Total Expenses', 'Operating Income']

In [11]:
# show share count
cmpy.get_shares_full(start="2024-01-01", end=None)

2024-01-06 00:00:00-05:00    2470000128
2024-01-06 00:00:00-05:00    2526560000
2024-01-13 00:00:00-05:00    2475239936
2024-01-16 00:00:00-05:00    2470180096
2024-01-16 00:00:00-05:00    2470000128
2024-02-09 00:00:00-05:00    2470000128
2024-02-09 00:00:00-05:00    2485779968
2024-02-23 00:00:00-05:00    2500000000
dtype: int64

In [30]:
# df_test = cmpy.get_income_stmt()
# df_test

,2024-01-31,2023-01-31,2022-01-31,2021-01-31
TaxEffectOfUnusualItems,0.0,-284130000.0,0.0,0.0
TaxRateForCalcs,0.12,0.21,0.019,0.017
NormalizedEBITDA,35583000000.0,7340000000.0,11351000000.0,5691000000.0
TotalUnusualItems,0.0,-1353000000.0,0.0,0.0
TotalUnusualItemsExcludingGoodwill,0.0,-1353000000.0,0.0,0.0
NetIncomeFromContinuingOperationNetMinorityInterest,29760000000.0,4368000000.0,9752000000.0,4332000000.0
ReconciledDepreciation,1508000000.0,1544000000.0,1174000000.0,1098000000.0
ReconciledCostOfRevenue,16621000000.0,11618000000.0,9439000000.0,6279000000.0
EBITDA,35583000000.0,5987000000.0,11351000000.0,5691000000.0
EBIT,34075000000.0,4443000000.0,10177000000.0,4593000000.0
NetInterestIncome,609000000.0,5000000.0,-207000000.0,-127000000.0
InterestExpense,257000000.0,262000000.0,236000000.0,184000000.0
InterestIncome,866000000.0,267000000.0,29000000.0,57000000.0
NormalizedIncome,29760000000.0,5436870000.0,9752000000.0,4332000000.0
NetIncomeFromContinuingAndDiscontinuedOperation,29760000000.0,4368000000.0,9752000000.0,4332000000.0
TotalExpenses,27950000000.0,21397000000.0,16873000000.0,12143000000.0
TotalOperatingIncomeAsReported,32972000000.0,4224000000.0,10041000000.0,4532000000.0
DilutedAverageShares,2494000000.0,2507000000.0,2535000000.0,2512000000.0
BasicAverageShares,2469000000.0,2487000000.0,2496000000.0,2468000000.0
DilutedEPS,11.93,1.74,3.85,1.725
BasicEPS,12.05,1.76,3.91,1.755
DilutedNIAvailtoComStockholders,29760000000.0,4368000000.0,9752000000.0,4332000000.0
NetIncomeCommonStockholders,29760000000.0,4368000000.0,9752000000.0,4332000000.0
NetIncome,29760000000.0,4368000000.0,9752000000.0,4332000000.0
NetIncomeIncludingNoncontrollingInterests,29760000000.0,4368000000.0,9752000000.0,4332000000.0
NetIncomeContinuousOperations,29760000000.0,4368000000.0,9752000000.0,4332000000.0
TaxProvision,4058000000.0,-187000000.0,189000000.0,77000000.0
PretaxIncome,33818000000.0,4181000000.0,9941000000.0,4409000000.0
OtherIncomeExpense,237000000.0,-1401000000.0,107000000.0,4000000.0
OtherNonOperatingIncomeExpenses,237000000.0,-48000000.0,107000000.0,4000000.0
SpecialIncomeCharges,0.0,-1353000000.0,0.0,0.0
RestructuringAndMergernAcquisition,0.0,1353000000.0,0.0,0.0
NetNonOperatingInterestIncomeExpense,609000000.0,5000000.0,-207000000.0,-127000000.0
InterestExpenseNonOperating,257000000.0,262000000.0,236000000.0,184000000.0
InterestIncomeNonOperating,866000000.0,267000000.0,29000000.0,57000000.0
OperatingIncome,32972000000.0,5577000000.0,10041000000.0,4532000000.0
OperatingExpense,11329000000.0,9779000000.0,7434000000.0,5864000000.0
ResearchAndDevelopment,8675000000.0,7339000000.0,5268000000.0,3924000000.0
SellingGeneralAndAdministration,2654000000.0,2440000000.0,2166000000.0,1940000000.0
GrossProfit,44301000000.0,15356000000.0,17475000000.0,10396000000.0
CostOfRevenue,16621000000.0,11618000000.0,9439000000.0,6279000000.0
TotalRevenue,60922000000.0,26974000000.0,26914000000.0,16675000000.0
OperatingRevenue,60922000000.0,26974000000.0,26914000000.0,16675000000.0

In [20]:
# Operating Revenue: 营业收入
# Cost Of Revenue: 营业成本
# Gross Profit: 营业毛利润
# Selling General And Administration: 市场、销售和管理费用
# --Selling And Marketing Expense
# --General And Administrative Expense
# Research And Development: 研发费用
# Operating Expense: 营业费用
# Operating Income: 营业利润

income_col = ['Operating Revenue', 'Cost Of Revenue', 'Gross Profit', 
              'Selling General And Administration', 
              'Research And Development', 
              'Operating Expense', 'Operating Income']
# income_col = ['Total Revenue', 'Gross Profit', 
#               'Total Expenses', 'Operating Income']
df_income = cmpy_income.loc[:, income_col]

num = 1e8
df_income = df_income / num
df_income = df_income.head(4)
df_income

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income
2024-03-31,907.53,484.82,422.71,64.68,79.03,143.71,279.0
2023-12-31,1195.75,647.2,548.55,67.86,76.96,144.82,403.73
2023-09-30,894.98,490.71,404.27,61.51,73.07,134.58,269.69
2023-06-30,817.97,453.84,364.13,59.73,74.42,134.15,229.98

In [21]:
total_income = df_income.sum()
# total_income
total_income = pd.DataFrame(total_income).T # 转置成行
total_income.index = [symbol]  # 设置行名为 'Total'
# total_income['Currency'] = cmpy.info['financialCurrency']
total_income
# 将新行添加到原 DataFrame
df_all = pd.concat([df_income, total_income], ignore_index=False)
df_all['Currency'] = cmpy.info['financialCurrency']
df_all

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency
2024-03-31 00:00:00,907.53,484.82,422.71,64.68,79.03,143.71,279.0,USD
2023-12-31 00:00:00,1195.75,647.2,548.55,67.86,76.96,144.82,403.73,USD
2023-09-30 00:00:00,894.98,490.71,404.27,61.51,73.07,134.58,269.69,USD
2023-06-30 00:00:00,817.97,453.84,364.13,59.73,74.42,134.15,229.98,USD
AAPL,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD

In [22]:
# income_col = ['Total Revenue', 'Total Expenses', 
#               'Gross Profit', 'Operating Income']
income_col = ['Operating Revenue', 'Cost Of Revenue', 'Gross Profit', 
              'Selling General And Administration', 
              'Research And Development', 
              'Operating Expense', 'Operating Income']

num = 1e8
df_all = pd.DataFrame(columns=income_col)
#金融、ETF
special_symbol = ['BRK.A', 'BRK.B', 'JPM', 'BAC', 
                  'WFC', 'RDS.A', 'AXP', 'BHP', 
                  'HSBC', 'MS', 'HDB', 'MUFG', 
                  'GS', 'UL', 'SCHW', 'BKNG', 
                  'ELV', 'ANTM', 'PGR', 'RY',
                  'C', 'TD', 'RIO', 'CB', 'TOT',
                   'CI', 'UBS', 'STLA']
df_name = [symbol for symbol in df_name if symbol not in special_symbol]
# df_name[:100]
for i in df_name[:100]:
    symbol = i
    # print(symbol)
    cmpy = yf.Ticker(symbol)
    # cmpy_income = cmpy.income_stmt
    cmpy_income = cmpy.quarterly_income_stmt
    cmpy_income = cmpy_income.T
    if 'Research And Development' not in cmpy_income.columns:
        cmpy_income['Research And Development'] = 0
    # cmpy_income
    if 'Selling General And Administration' not in cmpy_income.columns:
        cmpy_income['Selling General And Administration'] = 0
    
    df_income = cmpy_income.loc[:, income_col]
    df_income = df_income / num
    df_income = df_income.head(4)
    # df_income
    total_income = df_income.sum()
    # total_income
    total_income = pd.DataFrame(total_income).T # 转置成行
    total_income.index = [symbol]  # 设置行名为 'symbol'
    
    # total_income['Currency'] = cmpy.info['financialCurrency']
    # total_income
    df_income = pd.concat([df_income, total_income], ignore_index=False)
    df_income['Currency'] = cmpy.info['financialCurrency']
    # df_income['floatShares'] = cmpy.info['floatShares']
    df_income['sharesOutstanding'] = round(cmpy.info['sharesOutstanding'] / num, 2)
    
    df_all = pd.concat([df_all, df_income], ignore_index=False)
    # df_all
    
df_all

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding
2024-03-31 00:00:00,618.58,185.05,433.53,81.19,76.53,157.72,275.81,USD,74.32
2023-12-31 00:00:00,620.2,196.23,423.97,82.23,71.42,153.65,270.32,USD,74.32
2023-09-30 00:00:00,565.17,163.02,402.15,66.61,66.59,133.2,268.95,USD,74.32
2023-06-30 00:00:00,561.89,167.95,393.94,84.01,67.39,151.4,242.54,USD,74.32
MSFT,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32
...,...,...,...,...,...,...,...,...,...
2024-01-31 00:00:00,25.12704,10.38763,14.73941,2.90078,3.91427,8.71837,6.02104,USD,4.96
2023-10-31 00:00:00,27.16484,10.69768,16.46716,2.88936,4.06594,8.98266,7.4845,USD,4.96
2023-07-31 00:00:00,30.76495,11.1488,19.61615,3.34113,4.23751,10.08583,9.53032,USD,4.96
2023-04-30 00:00:00,32.6293,11.18384,21.44546,3.24251,4.15754,9.93026,11.5152,USD,4.96
ADI,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96

In [23]:
# 将索引转换为名为'symbol'的新列，并重置索引
df_all['symbol'] = df_all.index
df_all = df_all.reset_index(drop=True)
df_all

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol
0,618.58,185.05,433.53,81.19,76.53,157.72,275.81,USD,74.32,2024-03-31 00:00:00
1,620.2,196.23,423.97,82.23,71.42,153.65,270.32,USD,74.32,2023-12-31 00:00:00
2,565.17,163.02,402.15,66.61,66.59,133.2,268.95,USD,74.32,2023-09-30 00:00:00
3,561.89,167.95,393.94,84.01,67.39,151.4,242.54,USD,74.32,2023-06-30 00:00:00
4,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT
...,...,...,...,...,...,...,...,...,...,...
495,25.12704,10.38763,14.73941,2.90078,3.91427,8.71837,6.02104,USD,4.96,2024-01-31 00:00:00
496,27.16484,10.69768,16.46716,2.88936,4.06594,8.98266,7.4845,USD,4.96,2023-10-31 00:00:00
497,30.76495,11.1488,19.61615,3.34113,4.23751,10.08583,9.53032,USD,4.96,2023-07-31 00:00:00
498,32.6293,11.18384,21.44546,3.24251,4.15754,9.93026,11.5152,USD,4.96,2023-04-30 00:00:00
499,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI

In [81]:
# TSM, WMT, TTE
df_all.loc[450:500, :]

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol
450,32.218,5.17,29.173,7.377,11.772,19.144,10.029,USD,1.08,2023-12-31 00:00:00
451,32.244,4.364,29.263,6.405,10.753,17.153,12.11,USD,1.08,2023-09-30 00:00:00
452,30.888,4.049,27.532,6.52,10.853,17.367,10.165,USD,1.08,2023-06-30 00:00:00
453,30.461,4.575,27.046,6.011,11.012,17.018,10.028,USD,1.08,2023-03-31 00:00:00
454,125.811,18.158,113.014,26.313,44.39,70.682,42.332,USD,1.08,REGN
455,22.18,3.84,18.34,16.27,4.32,23.3,-4.96,USD,4.38,2023-12-31 00:00:00
456,33.97,4.59,29.38,7.07,4.19,14.42,14.96,USD,4.38,2023-09-30 00:00:00
457,24.84,4.32,20.52,7.61,4.51,15.29,5.23,USD,4.38,2023-06-30 00:00:00
458,18.18,4.28,13.9,6.93,4.2,13.95,-0.05,USD,4.38,2023-03-31 00:00:00
459,99.17,17.03,82.14,37.88,17.22,66.96,15.18,USD,4.38,ABNB
460,188.74,165.79,22.95,0.0,0.0,0.02,22.93,USD,2.42,2023-12-31 00:00:00
461,168.78,148.3,20.48,0.0,0.0,0.06,20.42,USD,2.42,2023-09-30 00:00:00
462,166.93,146.03,20.9,0.0,0.0,-0.45,21.35,USD,2.42,2023-06-30 00:00:00
463,151.26,130.8,20.46,0.0,0.0,NaN,20.46,USD,2.42,2023-03-31 00:00:00
464,675.71,590.92,84.79,0.0,0.0,-0.37,85.16,USD,2.42,LMT
465,118.46,72.0,46.46,10.66,5.33,19.68,26.78,USD,2.78,2024-01-31 00:00:00
466,151.57,96.54,55.03,12.26,6.06,17.81,37.22,USD,2.78,2023-10-31 00:00:00
467,155.37,96.24,59.13,11.1,5.28,19.48,39.65,USD,2.78,2023-07-31 00:00:00
468,171.58,107.3,64.28,13.3,5.47,22.4,41.88,USD,2.78,2023-04-30 00:00:00
469,596.98,372.08,224.9,47.32,22.14,79.37,145.53,USD,2.78,DE
470,47.26,47.61,-0.35,2.63,8.45,10.93,-11.28,USD,11.04,2023-11-30 00:00:00
471,40.1,44.45,-4.35,2.19,7.19,9.4,-13.75,USD,11.04,2023-08-31 00:00:00
472,37.52,44.2,-6.68,2.19,7.58,9.81,-16.49,USD,11.04,2023-05-31 00:00:00
473,36.93,48.99,-12.06,2.31,7.88,10.11,-22.17,USD,11.04,2023-02-28 00:00:00
474,161.81,185.25,-23.44,9.32,31.1,40.25,-63.69,USD,11.04,MU
475,89.473,68.321,25.932,6.48,0.0,11.637,14.295,USD,11.32,2023-12-31 00:00:00
476,88.674,66.544,27.192,6.357,0.0,11.324,15.868,USD,11.32,2023-09-30 00:00:00
477,86.929,65.618,26.065,6.043,0.0,10.852,15.213,USD,11.32,2023-06-30 00:00:00
478,82.118,64.377,22.821,6.204,0.0,10.885,11.936,USD,11.32,2023-03-31 00:00:00
479,347.194,264.86,102.01,25.084,0.0,44.698,57.312,USD,11.32,SBUX
480,521.41,413.18,108.23,47.33,0.0,44.88,63.35,USD,28.22,2023-12-31 00:00:00
481,532.69,406.32,126.37,44.58,0.0,45.55,80.82,USD,28.22,2023-09-30 00:00:00
482,485.38,397.3,88.08,38.34,0.0,41.27,46.81,USD,28.22,2023-06-30 00:00:00
483,561.82,403.78,158.04,37.47,0.0,38.53,119.51,USD,28.22,2023-03-31 00:00:00
484,2101.3,1620.58,480.72,167.72,0.0,170.23,310.49,USD,28.22,BP
485,55.09,32.68,22.86,0.0,0.0,11.83,11.03,USD,4.92,2023-12-31 00:00:00
486,53.96,32.87,20.95,0.0,0.0,10.99,9.96,USD,4.92,2023-09-30 00:00:00
487,58.94,33.37,25.39,0.0,0.0,10.82,14.57,USD,4.92,2023-06-30 00:00:00
488,59.37,32.07,27.17,0.0,0.0,9.91,17.26,USD,4.92,2023-03-31 00:00:00
489,227.36,130.99,96.37,0.0,0.0,43.55,52.82,USD,4.92,MMC
490,44.427,25.616,18.811,9.225,0.0,9.225,9.586,USD,4.11,2023-12-31 00:00:00
491,43.107,25.154,17.953,8.803,0.0,8.803,9.15,USD,4.11,2023-09-30 00:00:00
492,42.421,24.853,17.568,9.572,0.0,9.572,7.996,USD,4.11,2023-06-30 00:00:00
493,46.784,26.238,20.546,9.38,0.0,9.38,11.166,USD,4.11,2023-03-31 00:00:00
494,176.739,101.861,74.878,36.98,0.0,36.98,37.898,USD,4.11,ADP
495,25.12704,10.38763,14.73941,2.90078,3.91427,8.71837,6.02104,USD,4.96,2024-01-31 00:00:00
496,27.16484,10.69768,16.46716,2.88936,4.06594,8.98266,7.4845,USD,4.96,2023-10-31 00:00:00
497,30.76495,11.1488,19.61615,3.34113,4.23751,10.08583,9.53032,USD,4.96,2023-07-31 00:00:00
498,32.6293,11.18384,21.44546,3.24251,4.15754,9.93026,11.5152,USD,4.96,2023-04-30 00:00:00
499,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI

In [50]:
df_all.head(20)

   Total Revenue Total Expenses Gross Profit Operating Income Currency symbol
0        2275.83         1270.5      1587.35          1005.33      USD   MSFT
1        3857.06        2670.48      1736.71          1186.58      USD   AAPL
2         609.22         279.51       443.01           329.71      USD   NVDA
3        5747.85        5379.33       938.05           368.52      USD   AMZN
4        3073.94        2231.01      1740.62           842.93      USD   GOOG
5        3073.94        2231.01      1740.62           842.93      USD  GOOGL
6        1349.01          881.5      1089.43           467.51      USD   META
7    15362.06985     8749.45882   8433.42703       6612.61103      TWD    TSM
8        341.241        231.054      270.419          110.187      USD    LLY
9         358.19         193.68        246.9           164.51      USD   AVGO
10       2322.61        1296.87      1964.96          1025.74      DKK    NVO
11        333.51         108.92       266.39           224.59      USD      V
12        967.73         878.82        176.6            88.91      USD   TSLA
13       4747.37        4549.79       1164.2           197.58      USD    WMT
14       3716.22        3392.64       909.58           323.58      USD    UNH
15        250.98         104.68       190.76            146.3      USD     MA
16       3346.97         2909.5       841.42           437.47      USD    XOM
17       275.585        185.162      141.361           90.423      EUR   ASML
18        930.22         689.92       630.11            240.3      USD    JNJ
19        839.33         639.82       422.71           199.51      USD     PG

In [25]:
df_select = df_all.iloc[4::5]
df_select

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol
4,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT
9,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL
14,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA
19,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN
24,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG
...,...,...,...,...,...,...,...,...,...,...
479,346.147,264.211,101.091,25.426,0.0,45.406,55.685,USD,11.33,SBUX
484,2028.28,1607.68,420.6,172.47,0.0,176.39,244.21,USD,27.90,BP
489,232.86,133.62,99.23,0.0,0.0,44.42,54.81,USD,4.93,MMC
494,189.12,103.305,85.815,36.925,0.0,36.925,48.89,USD,4.09,ADP
499,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI

In [10]:
df_select.loc[200:300, :]

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol
204,3166.19,2694.12,472.07,134.34,12.87,164.72,307.35,USD,32.19,SHEL
209,497.8,144.11,366.01,136.64,118.12,264.81,101.2,USD,20.44,NVS
214,889.35,584.02,305.33,152.92,0.0,205.98,99.35,USD,18.34,DIS
219,572.33,204.79,367.54,127.14,77.71,207.58,159.96,USD,40.49,CSCO
224,773.79,301.88,483.7,213.11,0.0,341.29,142.41,USD,11.87,TMUS
229,362.92,161.37,201.55,24.88,86.63,121.93,79.62,USD,11.16,QCOM
234,8909.07,5770.48,3504.46,1520.44,520.51,2261.0,1243.46,CNY,25.00,BABA
239,542.28,325.17,217.11,56.34,160.46,216.8,0.31,USD,42.28,INTC
244,238.9,98.56,140.34,72.52,15.03,87.55,52.79,USD,7.40,DHR
249,150.94,33.09,117.85,51.91,26.42,83.14,34.71,USD,2.80,INTU
254,679.52,503.91,175.61,120.81,19.08,139.89,35.72,USD,10.93,GE
259,618.59,275.6,343.0,179.97,67.75,249.27,93.73,USD,9.17,IBM
264,1215.72,367.62,848.1,471.61,0.0,614.97,233.13,USD,39.62,CMCSA
269,1339.74,548.87,790.87,327.45,0.0,503.69,287.18,USD,42.04,VZ
274,264.85,140.42,124.43,17.07,30.85,47.92,76.51,USD,8.31,AMAT
279,670.6,437.97,232.63,63.71,21.08,102.97,129.66,USD,4.99,CAT
284,2415.39,1339.32,1084.04,199.69992,0.0,755.78,328.26,MXN,2.10,KOF
289,372.81,224.57,148.24,70.38,31.64,137.14,11.1,USD,20.76,UBER
294,584.97,249.55,335.42,147.71,106.79,301.83,33.59,USD,56.63,PFE
299,175.19,65.0,110.19,18.25,18.63,36.88,73.31,USD,9.10,TXN

In [26]:
df_merge = pd.merge(df_select, us_stock_name_df[['symbol', 'cname']], on='symbol', how='left')
# df_merge.reset_index(drop=True, inplace=True)  # 将索引转换为整数索引
df_merge

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
...,...,...,...,...,...,...,...,...,...,...,...
95,346.147,264.211,101.091,25.426,0.0,45.406,55.685,USD,11.33,SBUX,星巴克公司
96,2028.28,1607.68,420.6,172.47,0.0,176.39,244.21,USD,27.90,BP,英国石油公司
97,232.86,133.62,99.23,0.0,0.0,44.42,54.81,USD,4.93,MMC,威达信集团
98,189.12,103.305,85.815,36.925,0.0,36.925,48.89,USD,4.09,ADP,自动数据处理公司
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体

In [27]:
df_merge.head(20)

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
5,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,58.74,GOOGL,谷歌A类股
6,1414.79,264.9,1162.21,237.99,390.8,628.79,533.42,USD,21.91,META,"Meta Platforms, Inc."
7,22457.46827,7644.92619,12031.15208,553.11192,1432.13164,1983.82765,9392.45443,TWD,51.87,TSM,台湾积体电路制造公司
8,359.321,71.29,288.031,69.125,98.511,167.636,120.395,USD,9.50,LLY,礼来公司
9,388.65,128.04,260.61,28.16,63.66,110.2,150.41,USD,4.63,AVGO,博通
10,6206.27,374.99,2067.44,625.28,343.21,973.31,1094.13,DKK,44.55,NVO,诺和诺德公司
11,947.45,779.0,168.45,50.98,43.49,94.47,73.98,USD,31.89,TSLA,特斯拉
12,445.63,68.1,273.31,34.46,0.0,44.24,229.07,USD,15.74,V,维萨卡公司
13,6481.25,4901.42,1579.83,1309.71,0.0,1309.71,270.12,USD,80.60,WMT,沃尔玛公司
14,3751.85,2882.05,912.82,0.0,0.0,590.79,322.03,USD,9.20,UNH,美国联合健康集团
15,256.98,61.1,195.88,37.39,0.0,45.63,150.25,USD,9.22,MA,万事达卡公司
16,3314.64,2523.76,790.88,105.94,0.0,394.65,396.23,USD,44.86,XOM,埃克森美孚公司
17,896.59,281.27,615.32,219.32,152.98,372.3,243.02,USD,24.07,JNJ,强生公司
18,840.6,411.13,429.47,227.84,0.0,227.84,201.63,USD,23.60,PG,宝洁公司
19,261.023,126.828,134.195,11.263,40.645,51.908,82.287,EUR,3.95,ASML,阿斯麦公司

In [28]:
modify_item = ['TSM', 'WMT', 'TTE']
# for item in modify_item:
updated_tsm_data = {
    'Operating Revenue': 21617.35841,
    'Cost Of Revenue': 0,
    'Gross Profit': 11751.10628,
    'Selling General And Administration': 0,
    'Research And Development': 0,
    'Operating Expense': 2537.01600,
    'Operating Income': 9214.65606
}
tsm_id = df_merge[df_merge['symbol'] == 'TSM'].index[0]
df_merge.loc[tsm_id, income_col] = updated_tsm_data
# df_merge.loc[Cur_id, 'Currency'] = 'USD'
# df_modify = df_merge
df_merge

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
...,...,...,...,...,...,...,...,...,...,...,...
95,346.147,264.211,101.091,25.426,0.0,45.406,55.685,USD,11.33,SBUX,星巴克公司
96,2028.28,1607.68,420.6,172.47,0.0,176.39,244.21,USD,27.90,BP,英国石油公司
97,232.86,133.62,99.23,0.0,0.0,44.42,54.81,USD,4.93,MMC,威达信集团
98,189.12,103.305,85.815,36.925,0.0,36.925,48.89,USD,4.09,ADP,自动数据处理公司
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体

In [29]:
df_merge.loc[:10, :]

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
5,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,58.74,GOOGL,谷歌A类股
6,1414.79,264.9,1162.21,237.99,390.8,628.79,533.42,USD,21.91,META,"Meta Platforms, Inc."
7,21617.35841,0.0,11751.10628,0.0,0.0,2537.016,9214.65606,TWD,51.87,TSM,台湾积体电路制造公司
8,359.321,71.29,288.031,69.125,98.511,167.636,120.395,USD,9.50,LLY,礼来公司
9,388.65,128.04,260.61,28.16,63.66,110.2,150.41,USD,4.63,AVGO,博通
10,6206.27,374.99,2067.44,625.28,343.21,973.31,1094.13,DKK,44.55,NVO,诺和诺德公司

In [30]:
updated_wmt_data = {
    'Operating Revenue': 6481.25,
    'Cost Of Revenue': 4901.42,
    'Gross Profit': 1579.83,
    'Selling General And Administration': 1309.71,
    'Research And Development': 0,
    'Operating Expense': 1309.71,
    'Operating Income': 270.12
}
wmt_id = df_merge[df_merge['symbol'] == 'WMT'].index[0]
df_merge.loc[wmt_id, income_col] = updated_wmt_data
# df_merge.loc[Cur_id, 'Currency'] = 'USD'
# df_modify = df_merge
df_merge

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
...,...,...,...,...,...,...,...,...,...,...,...
95,346.147,264.211,101.091,25.426,0.0,45.406,55.685,USD,11.33,SBUX,星巴克公司
96,2028.28,1607.68,420.6,172.47,0.0,176.39,244.21,USD,27.90,BP,英国石油公司
97,232.86,133.62,99.23,0.0,0.0,44.42,54.81,USD,4.93,MMC,威达信集团
98,189.12,103.305,85.815,36.925,0.0,36.925,48.89,USD,4.09,ADP,自动数据处理公司
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体

In [31]:
df_merge.loc[:30, :]

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
5,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,58.74,GOOGL,谷歌A类股
6,1414.79,264.9,1162.21,237.99,390.8,628.79,533.42,USD,21.91,META,"Meta Platforms, Inc."
7,21617.35841,0.0,11751.10628,0.0,0.0,2537.016,9214.65606,TWD,51.87,TSM,台湾积体电路制造公司
8,359.321,71.29,288.031,69.125,98.511,167.636,120.395,USD,9.50,LLY,礼来公司
9,388.65,128.04,260.61,28.16,63.66,110.2,150.41,USD,4.63,AVGO,博通
10,6206.27,374.99,2067.44,625.28,343.21,973.31,1094.13,DKK,44.55,NVO,诺和诺德公司
11,947.45,779.0,168.45,50.98,43.49,94.47,73.98,USD,31.89,TSLA,特斯拉
12,445.63,68.1,273.31,34.46,0.0,44.24,229.07,USD,15.74,V,维萨卡公司
13,6481.25,4901.42,1579.83,1309.71,0.0,1309.71,270.12,USD,80.60,WMT,沃尔玛公司
14,3751.85,2882.05,912.82,0.0,0.0,590.79,322.03,USD,9.20,UNH,美国联合健康集团
15,256.98,61.1,195.88,37.39,0.0,45.63,150.25,USD,9.22,MA,万事达卡公司
16,3314.64,2523.76,790.88,105.94,0.0,394.65,396.23,USD,44.86,XOM,埃克森美孚公司
17,896.59,281.27,615.32,219.32,152.98,372.3,243.02,USD,24.07,JNJ,强生公司
18,840.6,411.13,429.47,227.84,0.0,227.84,201.63,USD,23.60,PG,宝洁公司
19,261.023,126.828,134.195,11.263,40.645,51.908,82.287,EUR,3.95,ASML,阿斯麦公司
20,1518.3,1009.94,508.36,269.1,0.0,296.19,212.17,USD,9.92,HD,家得宝公司
21,228.0,121.39,106.61,23.87,59.86,100.79,5.82,USD,16.16,AMD,美国超微公司
22,437129.85,350300.1,86829.75,38158.07,0.0,38158.07,48671.68,JPY,13.47,TM,丰田汽车公司
23,544.03,205.23,338.8,131.48,73.22,203.01,135.79,USD,17.66,ABBV,艾伯维公司
24,2488.28,2179.91,308.37,223.31,0.0,223.31,85.06,USD,4.44,COST,开市客公司
25,525.1,149.49,375.61,111.74,86.45,229.56,146.05,USD,27.49,ORCL,甲骨文公司
26,614.02,157.4,456.62,105.08,302.47,407.55,49.07,USD,25.33,MRK,默沙东集团
27,348.57,85.41,263.16,145.2,49.06,203.17,59.99,USD,9.71,CRM,赛富时公司
28,1946.51,1354.21,592.3,42.7,0.0,347.7,244.6,USD,18.43,CVX,雪佛龙公司
29,349.32234,198.88816,150.43418,44.80242,26.90956,71.71198,78.7222,USD,4.31,NFLX,奈飞公司
30,460.74,184.38,276.36,79.36,0.0,143.26,133.1,USD,43.08,KO,可口可乐公司

In [32]:
updated_tte_data = {
    'Operating Revenue': 2371.28,
    'Cost Of Revenue': 1558.03,
    'Gross Profit': 631.42,
    'Selling General And Administration': 0,
    'Research And Development': 0,
    'Operating Expense': 309.92,
    'Operating Income': 321.50
}
tte_id = df_merge[df_merge['symbol'] == 'TTE'].index[0]
df_merge.loc[tte_id, income_col] = updated_tte_data
# df_merge.loc[Cur_id, 'Currency'] = 'USD'
# df_modify = df_merge
df_merge

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2365.84,712.25,1653.59,314.04,281.93,595.97,1057.62,USD,74.32,MSFT,微软公司
1,3816.23,2076.57,1739.66,253.78,303.48,557.26,1182.4,USD,153.34,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,24.60,NVDA,英伟达公司
3,5907.4,4872.08,1035.32,553.75,0.0,561.47,473.85,USD,104.07,AMZN,亚马逊公司
4,3181.46,1364.32,1817.14,435.02,458.62,893.64,923.5,USD,56.17,GOOG,谷歌
...,...,...,...,...,...,...,...,...,...,...,...
95,346.147,264.211,101.091,25.426,0.0,45.406,55.685,USD,11.33,SBUX,星巴克公司
96,2028.28,1607.68,420.6,172.47,0.0,176.39,244.21,USD,27.90,BP,英国石油公司
97,232.86,133.62,99.23,0.0,0.0,44.42,54.81,USD,4.93,MMC,威达信集团
98,189.12,103.305,85.815,36.925,0.0,36.925,48.89,USD,4.09,ADP,自动数据处理公司
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体

In [33]:
df_merge.loc[50:, :]

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
50,695.2,512.82,182.38,121.51,19.84,141.35,41.03,USD,10.95,GE,通用电气公司
51,620.68,275.36,345.33,181.29,69.16,251.49,93.84,USD,9.19,IBM,IBM(国际商业机器有限公司)
52,1240.28,365.81,853.58,477.72,0.0,618.82,234.76,USD,39.14,CMCSA,康卡斯特公司
53,1340.43,542.55,797.88,333.82,0.0,511.33,286.55,USD,42.09,VZ,威讯通信公司
54,264.85,140.42,124.43,17.07,30.85,47.92,76.51,USD,8.31,AMAT,应用材料公司
55,669.97,434.37,235.6,64.85,21.56,98.06,137.54,USD,4.89,CAT,卡特彼勒公司
56,2510.17,1378.43,1139.52,199.69992,0.0,786.67,352.85,MXN,2.10,KOF,可口可乐凡萨瓶装
57,385.89,233.66,152.23,69.6,31.79,136.79,15.44,USD,20.90,UBER,优步科技有限公司
58,550.93,234.48,316.45,148.48,106.67,304.53,11.92,USD,56.67,PFE,辉瑞制药公司
59,168.01,65.5,102.51,18.06,18.86,36.92,65.59,USD,9.10,TXN,德州仪器公司
60,2371.28,1558.03,631.42,0.0,0.0,309.92,321.5,USD,23.08,TTE,TotalEnergies SE
61,94.78,20.03,74.75,42.87,22.38,65.25,9.5,USD,2.05,NOW,现在服务公司
62,515.81,287.33,228.48,75.01,0.0,168.62,59.86,USD,12.11,NKE,耐克公司
63,225.31,134.89,106.05,-0.15,0.0,14.3,91.75,USD,6.10,UNP,联合太平洋公司
64,2476.39205,917.23577,1559.15628,862.64492,109.52374,972.16866,586.98762,CNY,13.89,PDD,拼多多公司
65,281.82,99.31,196.01,67.29,50.69,126.34,69.67,USD,5.36,AMGN,安进公司
66,853.52,130.5,228.98,104.01,0.0,104.01,124.97,USD,15.55,PM,菲利普莫里斯国际公司
67,851.01,575.32,288.44,155.68,0.0,172.86,115.58,USD,5.72,LOW,劳氏公司
68,551.78,376.39,175.39,7.24,0.0,31.49,143.9,USD,11.70,COP,康菲石油公司
69,209.63,75.88,133.75,71.88,14.17,92.32,41.43,USD,3.81,SYK,史赛克公司
70,73.185,24.566,48.619,19.749,10.384,30.133,18.486,USD,3.55,ISRG,直觉外科公司
71,128.28,41.73,86.55,31.59,0.0,43.03,43.52,USD,3.13,SPGI,标普全球
72,897.39,734.66,162.73,0.0,0.0,80.6,82.13,USD,7.29,UPS,联合包裹服务公司
73,369.03,230.8,138.23,51.12,14.59,65.71,72.52,USD,6.51,HON,霍尼韦尔国际公司
74,23.05,1.13,21.92,7.02,13.95,20.97,0.95,USD,10.40,ARM,Arm Holdings Plc
75,597.14,275.31,321.83,182.62,0.0,174.53,147.3,USD,19.71,BUD,百威英博公司
76,82.11503,20.5914,61.52363,4.0192,0.0,29.80363,31.72,USD,9.26,PLD,"Prologis, Inc."
77,1223.17,497.46,725.71,287.2,0.0,479.13,246.58,USD,71.70,T,美国电话电报公司
78,183.44,96.5,86.94,19.58,0.0,21.1,65.84,USD,1.49,BLK,贝莱德集团
79,433.12,145.96,321.03,106.9,68.84,223.01,98.02,EUR,24.99,SNY,赛诺菲-安万特公司
80,142.41136,75.70314,66.70822,8.51601,18.06566,26.58167,40.12655,USD,1.31,LRCX,林氏研究公司
81,710.11,589.3,120.81,37.09,28.67,62.06,58.75,USD,13.30,RTX,RTX Corp.
82,271.3,100.32,170.98,0.0,0.0,82.55,88.43,USD,20.55,NEE,新纪元能源公司
83,764.42,687.65,76.77,50.25,35.04,85.29,-8.52,USD,6.14,BA,波音公司
84,236.56,148.88,87.68,39.16,7.64,46.8,40.88,USD,4.00,ETN,伊顿公司
85,323.2,111.5,211.7,105.88,27.02,150.29,61.41,USD,13.28,MDT,美敦力公司
86,378.06,264.23,113.83,73.75,0.0,73.75,40.08,USD,11.32,TJX,TJX公司
87,448.87,110.59,344.75,83.77,96.73,271.98,72.77,USD,20.27,BMY,百时美施贵宝公司
88,101.85,13.379,88.471,12.382,32.094,44.476,43.995,USD,2.58,VRTX,福泰制药
89,126033.52,94287.07,31746.45,20991.39,0.0,20883.18,10863.27,JPY,12.21,SONY,Sony Group Corp.
90,125.631,17.921,113.08,27.192,45.862,73.191,39.889,USD,1.08,REGN,再生元制药公司
91,102.41,17.55,84.86,38.96,17.77,68.62,16.24,USD,4.42,ABNB,爱彼迎
92,696.4,612.14,84.26,-0.16,0.0,-0.89,85.15,USD,2.40,LMT,洛克希德马丁公司
93,596.98,372.08,224.9,47.32,22.14,79.37,145.53,USD,2.78,DE,迪尔股份有限公司
94,183.12,183.71,-0.59,9.81,31.54,39.11,-39.7,USD,11.07,MU,美光科技公司
95,346.147,264.211,101.091,25.426,0.0,45.406,55.685,USD,11.33,SBUX,星巴克公司
96,2028.28,1607.68,420.6,172.47,0.0,176.39,244.21,USD,27.90,BP,英国石油公司
97,232.86,133.62,99.23,0.0,0.0,44.42,54.81,USD,4.93,MMC,威达信集团
98,189.12,103.305,85.815,36.925,0.0,36.925,48.89,USD,4.09,ADP,自动数据处理公司
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体

In [34]:
unique_currencies = list(df_merge['Currency'].unique())
unique_currencies =unique_currencies[1:]
unique_currencies

['TWD', 'DKK', 'EUR', 'JPY', 'CNY', 'MXN']

In [35]:
currency_counts = df_merge['Currency'].value_counts()
currency_counts

Currency
USD    90
EUR     3
JPY     2
CNY     2
TWD     1
DKK     1
MXN     1
Name: count, dtype: int64

In [37]:
from forex_python.converter import CurrencyRates

c = CurrencyRates()
rate_dict = c.get_rates('USD')
rate_dict

RatesNotAvailableError: Currency Rates Source Not Ready

In [64]:
rate_dict['TWD'] = 31.630037
rate_dict

{'EUR': 0.9286775631500743,
 'JPY': 150.33432392273403,
 'BGN': 1.8163075780089153,
 'CZK': 23.64413075780089,
 'DKK': 6.922919762258544,
 'GBP': 0.794994427934621,
 'HUF': 361.3763001485884,
 'PLN': 4.030460624071322,
 'RON': 4.622121099554235,
 'SEK': 10.462017087667162,
 'CHF': 0.8814078751857356,
 'ISK': 138.46582466567608,
 'NOK': 10.545598068350667,
 'TRY': 30.827544576523028,
 'AUD': 1.5338967310549776,
 'BRL': 4.973161218424963,
 'CAD': 1.348254086181278,
 'CNY': 7.193629271916791,
 'HKD': 7.8228083209509665,
 'IDR': 15636.497028231799,
 'INR': 83.00659361069837,
 'KRW': 1332.73588410104,
 'MXN': 17.044576523031203,
 'MYR': 4.780460624071322,
 'NZD': 1.638930163447251,
 'PHP': 55.96025260029718,
 'SGD': 1.3465824665676076,
 'THB': 36.059621099554235,
 'ZAR': 18.886979940564636,
 'TWD': 31.630037}

In [64]:
rate_dict['DKK']

6.922919762258544

In [113]:
# mask = df_merge['Currency'] == 'DKK'
# mask

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: Currency, Length: 100, dtype: bool

In [114]:
# mask.head(20)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Currency, dtype: bool

In [117]:
# Cur_id = df_merge.loc[df_merge['Currency'] == 'DKK'].index.tolist()
# Cur_id

[9]

In [123]:
Cur_id = df_merge.loc[df_merge['Currency'] == 'DKK'].index.tolist()
df_merge.loc[Cur_id, income_col] /= rate_dict['DKK']
df_merge.loc[Cur_id, 'Currency'] = 'USD'
# df_merge

In [65]:
for item in unique_currencies:
    Cur_id = df_merge.loc[df_merge['Currency'] == item].index.tolist()
    df_merge.loc[Cur_id, income_col] /= rate_dict[item]
    df_merge.loc[Cur_id, 'Currency'] = item + '/USD'
df_trans = df_merge
df_trans

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2275.83,688.48,1587.35,306.78,275.24,582.02,1005.33,USD,74.30,MSFT,微软公司
1,3857.06,2120.35,1736.71,251.11,299.02,550.13,1186.58,USD,154.42,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,25.00,NVDA,英伟达公司
3,5747.85,4809.8,938.05,561.86,0.0,569.53,368.52,USD,103.87,AMZN,亚马逊公司
4,3073.94,1333.32,1740.62,443.42,454.27,897.69,842.93,USD,56.71,GOOG,谷歌
...,...,...,...,...,...,...,...,...,...,...,...
95,347.194,264.86,102.01,25.084,0.0,44.698,57.312,USD,11.32,SBUX,星巴克公司
96,2101.3,1620.58,480.72,167.72,0.0,170.23,310.49,USD,28.21,BP,英国石油公司
97,227.36,130.99,96.37,0.0,0.0,43.55,52.82,USD,4.92,MMC,威达信集团
98,176.739,101.861,74.878,36.98,0.0,36.98,37.898,USD,4.11,ADP,自动数据处理公司
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体

In [110]:
# df_dkk = df_merge.loc[df_merge['Currency'] == 'DKK']
# df_dkk.loc[:, income_col] /= rate_dict['DKK']
# df_dkk.loc[:, 'Currency'] = 'USD'
# df_dkk

,Total Revenue,Total Expenses,Gross Profit,Operating Income,Currency,symbol,cname
9,335.495727,187.329919,283.833999,148.165808,USD,NVO,诺和诺德公司

In [66]:
df_trans.loc[:50, :]

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname
0,2275.83,688.48,1587.35,306.78,275.24,582.02,1005.33,USD,74.30,MSFT,微软公司
1,3857.06,2120.35,1736.71,251.11,299.02,550.13,1186.58,USD,154.42,AAPL,苹果公司
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,25.00,NVDA,英伟达公司
3,5747.85,4809.8,938.05,561.86,0.0,569.53,368.52,USD,103.87,AMZN,亚马逊公司
4,3073.94,1333.32,1740.62,443.42,454.27,897.69,842.93,USD,56.71,GOOG,谷歌
5,3073.94,1333.32,1740.62,443.42,454.27,897.69,842.93,USD,58.93,GOOGL,谷歌A类股
6,1338.44,259.58,1089.43,237.09,384.83,621.92,467.51,USD,22.00,META,"Meta Platforms, Inc."
7,683.443981,0.0,371.517311,0.0,0.0,80.209075,291.326123,TWD/USD,51.87,TSM,台湾积体电路制造公司
8,341.241,70.822,270.419,67.098,93.134,160.232,110.187,USD,9.50,LLY,礼来公司
9,388.65,128.04,260.61,28.16,63.66,110.2,150.41,USD,4.63,AVGO,博通
10,879.173847,51.661728,283.833999,88.976909,46.863175,135.668191,148.165808,DKK/USD,44.62,NVO,诺和诺德公司
11,967.73,791.13,176.6,48.0,39.69,87.69,88.91,USD,31.85,TSLA,特斯拉
12,436.26,67.12,266.39,32.17,0.0,41.8,224.59,USD,15.82,V,维萨卡公司
13,6481.25,4901.42,1579.83,1309.71,0.0,1309.71,270.12,USD,80.53,WMT,沃尔玛公司
14,3675.33,2806.64,909.58,0.0,0.0,586.0,323.58,USD,9.22,UNH,美国联合健康集团
15,250.98,60.22,190.76,36.47,0.0,44.46,146.3,USD,9.26,MA,万事达卡公司
16,3346.97,2505.55,841.42,106.33,0.0,403.95,437.47,USD,39.68,XOM,埃克森美孚公司
17,930.22,300.11,630.11,236.13,153.68,389.81,240.3,USD,24.10,JNJ,强生公司
18,839.33,416.62,422.71,223.2,0.0,223.2,199.51,USD,23.53,PG,宝洁公司
19,296.749928,144.532403,152.217525,11.988014,42.862024,54.850038,97.367486,EUR/USD,3.95,ASML,阿斯麦公司
20,1526.69,1017.09,509.6,265.98,0.0,292.71,216.89,USD,9.91,HD,家得宝公司
21,226.8,122.2,104.6,23.52,58.72,100.59,4.01,USD,16.16,AMD,美国超微公司
22,2907.718202,2330.140522,577.57768,253.82141,0.0,253.82141,323.75627,JPY/USD,13.48,TM,丰田汽车公司
23,543.18,204.15,339.03,128.72,76.75,203.68,135.35,USD,17.66,ABBV,艾伯维公司
24,2488.28,2179.91,308.37,223.31,0.0,223.31,85.06,USD,4.44,COST,开市客公司
25,525.1,149.49,375.61,111.74,86.45,229.56,146.05,USD,27.49,ORCL,甲骨文公司
26,601.14,161.26,439.88,105.04,305.31,410.35,29.53,USD,25.33,MRK,默沙东集团
27,348.57,85.41,263.16,145.2,49.06,203.17,59.99,USD,9.70,CRM,赛富时公司
28,1969.13,1365.22,603.91,41.41,0.0,341.62,262.29,USD,18.57,CVX,雪佛龙公司
29,337.23297,197.15368,140.07929,43.78168,26.75758,70.53926,69.54003,USD,4.33,NFLX,奈飞公司
30,457.54,185.2,272.34,79.3,0.0,143.02,129.32,USD,43.12,KO,可口可乐公司
31,194.09,23.54,170.55,67.64,34.73,104.05,66.5,USD,4.53,ADBE,Adobe
32,645.88246,435.9484,209.93406,110.0892,0.0,122.1173,87.81676,USD,6.27,ACN,埃森哲公司
33,428.57,257.57,171.0,84.45,13.37,97.82,73.18,USD,3.81,TMO,赛默飞世尔科技公司
34,914.71,418.81,495.9,366.77,0.0,366.77,129.13,USD,13.74,PEP,百事可乐公司
35,328.54,174.92,153.62,31.31,1.46,70.93,82.69,USD,4.82,LIN,Linde Plc
36,336.047744,93.401632,242.646112,109.736688,68.096832,178.016576,64.629536,EUR/USD,11.67,SAP,SAP
37,251.781,109.312,145.625,24.352,0.0,28.169,117.456,USD,7.22,MCD,麦当劳公司
38,458.11,82.68,375.43,182.22,109.35,288.21,87.22,USD,31.00,AZN,阿斯利康公司
39,401.09,179.75,221.34,109.49,27.41,156.56,64.78,USD,17.35,ABT,雅培公司
40,3166.19,2694.12,472.07,134.34,12.87,164.72,307.35,USD,32.19,SHEL,Shell Plc
41,497.8,144.11,366.01,136.64,118.12,264.81,101.2,USD,20.44,NVS,诺华公司
42,889.35,584.02,305.33,152.92,0.0,205.98,99.35,USD,18.34,DIS,沃特迪士尼公司
43,572.33,204.79,367.54,127.14,77.71,207.58,159.96,USD,40.49,CSCO,思科系统公司
44,773.79,301.88,483.7,213.11,0.0,341.29,142.41,USD,11.87,TMUS,"T-Mobile US, Inc."
45,362.92,161.37,201.55,24.88,86.63,121.93,79.62,USD,11.16,QCOM,高通公司
46,1238.466658,802.16533,487.161608,211.359238,72.357079,314.305883,172.855725,CNY/USD,25.00,BABA,阿里巴巴
47,542.28,325.17,217.11,56.34,160.46,216.8,0.31,USD,42.28,INTC,英特尔公司
48,238.9,98.56,140.34,72.52,15.03,87.55,52.79,USD,7.40,DHR,丹纳赫公司
49,150.94,33.09,117.85,51.91,26.42,83.14,34.71,USD,2.80,INTU,财捷集团
50,679.52,503.91,175.61,120.81,19.08,139.89,35.72,USD,10.93,GE,通用电气公司

In [68]:
df_trans['gross_margin'] = df_trans["Gross Profit"] / df_trans["Operating Revenue"]
# df_trans['gross_margin_percent'] = (df_trans['gross_margin'] * 100).round(2).astype(str) + '%'

# 定义一个函数，用于将小数转换为百分比格式，并保留两位小数
def to_percentage(x):
    return "{:.2f}%".format(x * 100)

# 应用这个函数到特定的列上
df_trans['gross_margin'] = df_trans['gross_margin'].apply(to_percentage)
df_trans

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname,gross_margin
0,2275.83,688.48,1587.35,306.78,275.24,582.02,1005.33,USD,74.30,MSFT,微软公司,69.75%
1,3857.06,2120.35,1736.71,251.11,299.02,550.13,1186.58,USD,154.42,AAPL,苹果公司,45.03%
2,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,25.00,NVDA,英伟达公司,72.72%
3,5747.85,4809.8,938.05,561.86,0.0,569.53,368.52,USD,103.87,AMZN,亚马逊公司,16.32%
4,3073.94,1333.32,1740.62,443.42,454.27,897.69,842.93,USD,56.71,GOOG,谷歌,56.63%
...,...,...,...,...,...,...,...,...,...,...,...,...
95,347.194,264.86,102.01,25.084,0.0,44.698,57.312,USD,11.32,SBUX,星巴克公司,29.38%
96,2101.3,1620.58,480.72,167.72,0.0,170.23,310.49,USD,28.21,BP,英国石油公司,22.88%
97,227.36,130.99,96.37,0.0,0.0,43.55,52.82,USD,4.92,MMC,威达信集团,42.39%
98,176.739,101.861,74.878,36.98,0.0,36.98,37.898,USD,4.11,ADP,自动数据处理公司,42.37%
99,115.68613,43.41795,72.26818,12.37378,16.37526,37.71712,34.55106,USD,4.96,ADI,亚德诺半导体,62.47%

In [69]:
df_sorted = df_trans.sort_values(by='Operating Income', ascending=False, ignore_index=True)
df_sorted.head(10)

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income,Currency,sharesOutstanding,symbol,cname,gross_margin
0,3857.06,2120.35,1736.71,251.11,299.02,550.13,1186.58,USD,154.42,AAPL,苹果公司,45.03%
1,2275.83,688.48,1587.35,306.78,275.24,582.02,1005.33,USD,74.30,MSFT,微软公司,69.75%
2,3073.94,1333.32,1740.62,443.42,454.27,897.69,842.93,USD,56.71,GOOG,谷歌,56.63%
3,3073.94,1333.32,1740.62,443.42,454.27,897.69,842.93,USD,58.93,GOOGL,谷歌A类股,56.63%
4,1338.44,259.58,1089.43,237.09,384.83,621.92,467.51,USD,22.00,META,"Meta Platforms, Inc.",81.40%
5,3346.97,2505.55,841.42,106.33,0.0,403.95,437.47,USD,39.68,XOM,埃克森美孚公司,25.14%
6,5747.85,4809.8,938.05,561.86,0.0,569.53,368.52,USD,103.87,AMZN,亚马逊公司,16.32%
7,609.22,166.21,443.01,26.56,86.74,113.3,329.71,USD,25.00,NVDA,英伟达公司,72.72%
8,2907.718202,2330.140522,577.57768,253.82141,0.0,253.82141,323.75627,JPY/USD,13.48,TM,丰田汽车公司,19.86%
9,3675.33,2806.64,909.58,0.0,0.0,586.0,323.58,USD,9.22,UNH,美国联合健康集团,24.75%

In [71]:
new_col = ['Operating Revenue', 'Gross Profit', 'Operating Expense', 
           'Operating Income', 'sharesOutstanding', 'gross_margin',
           'symbol', 'cname']
df_sorted = df_sorted[new_col]
df_sorted.loc[:50, :]

,Operating Revenue,Gross Profit,Operating Expense,Operating Income,sharesOutstanding,gross_margin,symbol,cname
0,3857.06,1736.71,550.13,1186.58,154.42,45.03%,AAPL,苹果公司
1,2275.83,1587.35,582.02,1005.33,74.30,69.75%,MSFT,微软公司
2,3073.94,1740.62,897.69,842.93,56.71,56.63%,GOOG,谷歌
3,3073.94,1740.62,897.69,842.93,58.93,56.63%,GOOGL,谷歌A类股
4,1338.44,1089.43,621.92,467.51,22.00,81.40%,META,"Meta Platforms, Inc."
5,3346.97,841.42,403.95,437.47,39.68,25.14%,XOM,埃克森美孚公司
6,5747.85,938.05,569.53,368.52,103.87,16.32%,AMZN,亚马逊公司
7,609.22,443.01,113.3,329.71,25.00,72.72%,NVDA,英伟达公司
8,2907.718202,577.57768,253.82141,323.75627,13.48,19.86%,TM,丰田汽车公司
9,3675.33,909.58,586.0,323.58,9.22,24.75%,UNH,美国联合健康集团
10,2371.28,631.42,309.92,321.5,23.27,26.63%,TTE,TotalEnergies SE
11,2101.3,480.72,170.23,310.49,28.21,22.88%,BP,英国石油公司
12,3166.19,472.07,164.72,307.35,32.19,14.91%,SHEL,Shell Plc
13,683.443981,371.517311,80.209075,291.326123,51.87,54.36%,TSM,台湾积体电路制造公司
14,1339.74,790.87,503.69,287.18,42.04,59.03%,VZ,威讯通信公司
15,6481.25,1579.83,1309.71,270.12,80.53,24.38%,WMT,沃尔玛公司
16,1969.13,603.91,341.62,262.29,18.57,30.67%,CVX,雪佛龙公司
17,1224.28,723.05,476.51,246.54,71.53,59.06%,T,美国电话电报公司
18,930.22,630.11,389.81,240.3,24.10,67.74%,JNJ,强生公司
19,1215.72,848.1,614.97,233.13,39.62,69.76%,CMCSA,康卡斯特公司
20,436.26,266.39,41.8,224.59,15.82,61.06%,V,维萨卡公司
21,1526.69,509.6,292.71,216.89,9.91,33.38%,HD,家得宝公司
22,839.33,422.71,223.2,199.51,23.53,50.36%,PG,宝洁公司
23,1238.466658,487.161608,314.305883,172.855725,25.00,39.34%,BABA,阿里巴巴
24,572.33,367.54,207.58,159.96,40.49,64.22%,CSCO,思科系统公司
25,388.65,260.61,110.2,150.41,4.63,67.06%,AVGO,博通
26,561.41,182.03,31.77,150.26,11.76,32.42%,COP,康菲石油公司
27,879.173847,283.833999,135.668191,148.165808,44.62,32.28%,NVO,诺和诺德公司
28,250.98,190.76,44.46,146.3,9.26,76.01%,MA,万事达卡公司
29,525.1,375.61,229.56,146.05,27.49,71.53%,ORCL,甲骨文公司
30,593.8,319.85,173.93,145.92,19.74,53.86%,BUD,百威英博公司
31,596.98,224.9,79.37,145.53,2.78,37.67%,DE,迪尔股份有限公司
32,773.79,483.7,341.29,142.41,11.87,62.51%,TMUS,"T-Mobile US, Inc."
33,543.18,339.03,203.68,135.35,17.66,62.42%,ABBV,艾伯维公司
34,670.6,232.63,102.97,129.66,4.99,34.69%,CAT,卡特彼勒公司
35,457.54,272.34,143.02,129.32,43.12,59.52%,KO,可口可乐公司
36,914.71,495.9,366.77,129.13,13.74,54.21%,PEP,百事可乐公司
37,958.77,222.81,101.05,121.76,15.52,23.24%,PM,菲利普莫里斯国际公司
38,251.781,145.625,28.169,117.456,7.22,57.84%,MCD,麦当劳公司
39,888.35,300.74,185.0,115.74,5.74,33.85%,LOW,劳氏公司
40,463.77776,346.815744,234.914688,111.901056,24.97,74.78%,SNY,赛诺菲-安万特公司
41,341.241,270.419,160.232,110.187,9.50,79.25%,LLY,礼来公司
42,497.8,366.01,264.81,101.2,20.44,73.53%,NVS,诺华公司
43,889.35,305.33,205.98,99.35,18.34,34.33%,DIS,沃特迪士尼公司
44,281.15,179.78,81.46,98.32,20.52,63.94%,NEE,新纪元能源公司
45,296.749928,152.217525,54.850038,97.367486,3.95,51.29%,ASML,阿斯麦公司
46,618.59,343.0,249.27,93.73,9.17,55.45%,IBM,IBM(国际商业机器有限公司)
47,909.58,172.31,80.9,91.41,7.27,18.94%,UPS,联合包裹服务公司
48,225.71,105.29,14.47,90.82,6.10,46.65%,UNP,联合太平洋公司
49,967.73,176.6,87.69,88.91,31.85,18.25%,TSLA,特斯拉
50,645.88246,209.93406,122.1173,87.81676,6.27,32.50%,ACN,埃森哲公司

In [132]:
df_merge.loc[20:50, :]

,Total Revenue,Total Expenses,Gross Profit,Operating Income,Currency,symbol,cname
20,543.18,407.83,339.03,135.35,USD,ABBV,艾伯维公司
21,2456.52,2373.05,303.78,83.47,USD,COST,开市客公司
22,516.28,373.32,371.09,142.96,USD,ORCL,甲骨文公司
23,601.14,571.61,439.88,29.53,USD,MRK,默沙东集团
24,348.57,288.58,263.16,59.99,USD,CRM,赛富时公司
25,1969.13,1706.84,603.91,262.29,USD,CVX,雪佛龙公司
26,337.23297,267.69294,140.07929,69.54003,USD,NFLX,奈飞公司
27,457.54,328.22,272.34,129.32,USD,KO,可口可乐公司
28,194.09,127.59,170.55,66.5,USD,ADBE,Adobe
29,645.88246,558.0657,209.93406,87.81676,USD,ACN,埃森哲公司
30,428.57,355.39,171.0,73.18,USD,TMO,赛默飞世尔科技公司
31,914.71,785.58,495.9,129.13,USD,PEP,百事可乐公司
32,328.54,245.85,153.62,82.69,USD,LIN,Linde Plc
33,336.047744,271.418208,242.646112,64.629536,USD,SAP,SAP
34,254.937,137.481,145.625,117.456,USD,MCD,麦当劳公司
35,458.11,370.89,375.43,87.22,USD,AZN,阿斯利康公司
36,401.09,336.31,221.34,64.78,USD,ABT,雅培公司
37,510.12,408.92,366.01,101.2,USD,NVS,诺华公司
38,889.35,790.0,305.33,99.35,USD,DIS,沃特迪士尼公司
39,572.33,412.37,367.54,159.96,USD,CSCO,思科系统公司
40,785.58,643.17,483.7,142.41,USD,TMUS,"T-Mobile US, Inc."
41,362.92,283.3,201.55,79.62,USD,QCOM,高通公司
42,1289.326938,1116.471213,487.161608,172.855725,USD,BABA,阿里巴巴
43,542.28,541.97,217.11,0.31,USD,INTC,英特尔公司
44,238.9,186.11,140.34,52.79,USD,DHR,丹纳赫公司
45,150.94,116.23,117.85,34.71,USD,INTU,财捷集团
46,679.52,643.8,175.61,35.72,USD,GE,通用电气公司
47,618.59,524.87,343.0,93.73,USD,IBM,IBM(国际商业机器有限公司)
48,1215.72,982.59,848.1,233.13,USD,CMCSA,康卡斯特公司
49,1339.74,1052.56,790.87,287.18,USD,VZ,威讯通信公司
50,264.85,188.34,124.43,76.51,USD,AMAT,应用材料公司

In [63]:
from forex_python.bitcoin import BtcConverter

b = BtcConverter() 
b.get_latest_price('USD')

72164.4182

In [19]:
appl_income = appl.quarterly_income_stmt
# appl_income = appl.income_stmt
appl_income

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.159,0.149715,0.125,0.149,0.158
Normalized EBITDA,43221000000.0,30653000000.0,26783000000.0,32210000000.0,38932000000.0
Net Income From Continuing Operation Net Minority Interest,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Reconciled Depreciation,2848000000.0,2653000000.0,3052000000.0,2898000000.0,2916000000.0
Reconciled Cost Of Revenue,64720000000.0,49071000000.0,45384000000.0,52860000000.0,66822000000.0
EBITDA,43221000000.0,30653000000.0,26783000000.0,32210000000.0,38932000000.0
EBIT,40373000000.0,28000000000.0,23731000000.0,29312000000.0,36016000000.0
Net Interest Income,NaN,-18000000.0,-18000000.0,-12000000.0,-135000000.0
Interest Expense,NaN,1002000000.0,998000000.0,930000000.0,1003000000.0
Interest Income,NaN,984000000.0,980000000.0,918000000.0,868000000.0
Normalized Income,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income From Continuing And Discontinued Operation,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Total Expenses,79202000000.0,62529000000.0,58799000000.0,66518000000.0,81138000000.0
Total Operating Income As Reported,40373000000.0,26969000000.0,22998000000.0,28318000000.0,36016000000.0
Diluted Average Shares,15576641000.0,15672400000.0,15775021000.0,15847050000.0,15955718000.0
Basic Average Shares,15509763000.0,15599434000.0,15697614000.0,15787154000.0,15892723000.0
Diluted EPS,2.18,1.46,1.26,1.52,1.88
Basic EPS,2.19,1.47,1.27,1.53,1.89
Diluted NI Availto Com Stockholders,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income Common Stockholders,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income Including Noncontrolling Interests,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Net Income Continuous Operations,33916000000.0,22956000000.0,19881000000.0,24160000000.0,29998000000.0
Tax Provision,6407000000.0,4042000000.0,2852000000.0,4222000000.0,5625000000.0
Pretax Income,40323000000.0,26998000000.0,22733000000.0,28382000000.0,35623000000.0
Other Income Expense,-50000000.0,47000000.0,-247000000.0,76000000.0,-393000000.0
Other Non Operating Income Expenses,-50000000.0,47000000.0,-247000000.0,76000000.0,-393000000.0
Net Non Operating Interest Income Expense,NaN,-18000000.0,-18000000.0,-12000000.0,-135000000.0
Interest Expense Non Operating,NaN,1002000000.0,998000000.0,930000000.0,1003000000.0
Interest Income Non Operating,NaN,984000000.0,980000000.0,918000000.0,868000000.0
Operating Income,40373000000.0,26969000000.0,22998000000.0,28318000000.0,36016000000.0
Operating Expense,14482000000.0,13458000000.0,13415000000.0,13658000000.0,14316000000.0
Research And Development,7696000000.0,7307000000.0,7442000000.0,7457000000.0,7709000000.0
Selling General And Administration,6786000000.0,6151000000.0,5973000000.0,6201000000.0,6607000000.0
Gross Profit,54855000000.0,40427000000.0,36413000000.0,41976000000.0,50332000000.0
Cost Of Revenue,64720000000.0,49071000000.0,45384000000.0,52860000000.0,66822000000.0
Total Revenue,119575000000.0,89498000000.0,81797000000.0,94836000000.0,117154000000.0
Operating Revenue,119575000000.0,89498000000.0,81797000000.0,94836000000.0,117154000000.0

In [11]:
appl_income = appl_income.T
appl_income

,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,Net Interest Income,Interest Expense,...,Interest Expense Non Operating,Interest Income Non Operating,Operating Income,Operating Expense,Research And Development,Selling General And Administration,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue
2023-12-31,0.0,0.159,43221000000.0,33916000000.0,2848000000.0,64720000000.0,43221000000.0,40373000000.0,NaN,NaN,...,NaN,NaN,40373000000.0,14482000000.0,7696000000.0,6786000000.0,54855000000.0,64720000000.0,119575000000.0,119575000000.0
2023-09-30,0.0,0.149715,30653000000.0,22956000000.0,2653000000.0,49071000000.0,30653000000.0,28000000000.0,-18000000.0,1002000000.0,...,1002000000.0,984000000.0,26969000000.0,13458000000.0,7307000000.0,6151000000.0,40427000000.0,49071000000.0,89498000000.0,89498000000.0
2023-06-30,0.0,0.125,26783000000.0,19881000000.0,3052000000.0,45384000000.0,26783000000.0,23731000000.0,-18000000.0,998000000.0,...,998000000.0,980000000.0,22998000000.0,13415000000.0,7442000000.0,5973000000.0,36413000000.0,45384000000.0,81797000000.0,81797000000.0
2023-03-31,0.0,0.149,32210000000.0,24160000000.0,2898000000.0,52860000000.0,32210000000.0,29312000000.0,-12000000.0,930000000.0,...,930000000.0,918000000.0,28318000000.0,13658000000.0,7457000000.0,6201000000.0,41976000000.0,52860000000.0,94836000000.0,94836000000.0
2022-12-31,0.0,0.158,38932000000.0,29998000000.0,2916000000.0,66822000000.0,38932000000.0,36016000000.0,-135000000.0,1003000000.0,...,1003000000.0,868000000.0,36016000000.0,14316000000.0,7709000000.0,6607000000.0,50332000000.0,66822000000.0,117154000000.0,117154000000.0

In [12]:
# Operating Revenue: 营业收入
# Cost Of Revenue: 营业成本
# Gross Profit: 营业毛利润
# Selling General And Administration: 市场、销售和管理费用
# Research And Development: 研发费用
# Operating Expense: 营业支出总计
# Operating Income: 营业利润

income_col = ['Operating Revenue', 'Cost Of Revenue', 'Gross Profit', 
              'Selling General And Administration', 
              'Research And Development', 
              'Operating Expense', 'Operating Income']
df_appl_income = appl_income.loc[:, income_col]
df_appl_income

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income
2023-12-31,119575000000.0,64720000000.0,54855000000.0,6786000000.0,7696000000.0,14482000000.0,40373000000.0
2023-09-30,89498000000.0,49071000000.0,40427000000.0,6151000000.0,7307000000.0,13458000000.0,26969000000.0
2023-06-30,81797000000.0,45384000000.0,36413000000.0,5973000000.0,7442000000.0,13415000000.0,22998000000.0
2023-03-31,94836000000.0,52860000000.0,41976000000.0,6201000000.0,7457000000.0,13658000000.0,28318000000.0
2022-12-31,117154000000.0,66822000000.0,50332000000.0,6607000000.0,7709000000.0,14316000000.0,36016000000.0

In [13]:
num = 1e8
df_appl_income = df_appl_income / num
df_appl_income

,Operating Revenue,Cost Of Revenue,Gross Profit,Selling General And Administration,Research And Development,Operating Expense,Operating Income
2023-12-31,1195.75,647.2,548.55,67.86,76.96,144.82,403.73
2023-09-30,894.98,490.71,404.27,61.51,73.07,134.58,269.69
2023-06-30,817.97,453.84,364.13,59.73,74.42,134.15,229.98
2023-03-31,948.36,528.6,419.76,62.01,74.57,136.58,283.18
2022-12-31,1171.54,668.22,503.32,66.07,77.09,143.16,360.16

In [14]:
df_appl_income.index

DatetimeIndex(['2023-12-31', '2023-09-30', '2023-06-30', '2023-03-31',
               '2022-12-31'],
              dtype='datetime64[ns]', freq=None)

In [17]:
# show financials:
# - income statement
# msft.income_stmt
df_income = msft.quarterly_income_stmt
df_income

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Tax Effect Of Unusual Items,-29160000.0,-20700000.0,20855987.382214,30780000.0,-44080000.0
Tax Rate For Calcs,0.18,0.18,0.187892,0.19,0.19
Normalized EBITDA,33556000000.0,31845000000.0,28972000000.0,26556000000.0,24709000000.0
Total Unusual Items,-162000000.0,-115000000.0,111000000.0,162000000.0,-232000000.0
Total Unusual Items Excluding Goodwill,-162000000.0,-115000000.0,111000000.0,162000000.0,-232000000.0
Net Income From Continuing Operation Net Minority Interest,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Reconciled Depreciation,5959000000.0,3921000000.0,3874000000.0,3549000000.0,3648000000.0
Reconciled Cost Of Revenue,19623000000.0,16302000000.0,16795000000.0,16128000000.0,17488000000.0
EBITDA,33394000000.0,31730000000.0,29083000000.0,26718000000.0,24477000000.0
EBIT,27435000000.0,27809000000.0,25209000000.0,23169000000.0,20829000000.0
Net Interest Income,-175000000.0,641000000.0,423000000.0,252000000.0,210000000.0
Interest Expense,909000000.0,525000000.0,482000000.0,496000000.0,490000000.0
Interest Income,734000000.0,1166000000.0,905000000.0,748000000.0,700000000.0
Normalized Income,22002840000.0,22385300000.0,19990855987.382214,18167780000.0,16612920000.0
Net Income From Continuing And Discontinued Operation,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Total Expenses,34988000000.0,29622000000.0,31935000000.0,30505000000.0,32348000000.0
Total Operating Income As Reported,27032000000.0,26895000000.0,24254000000.0,22352000000.0,20399000000.0
Diluted Average Shares,7468000000.0,7462000000.0,7467000000.0,7464000000.0,7473000000.0
Basic Average Shares,7432000000.0,7429000000.0,7434000000.0,7441000000.0,7451000000.0
Diluted EPS,2.93,2.99,2.69,2.45,2.2
Basic EPS,2.94,3.0,2.7,2.46,2.2
Diluted NI Availto Com Stockholders,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Net Income Common Stockholders,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Net Income,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Net Income Including Noncontrolling Interests,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Net Income Continuous Operations,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0
Tax Provision,4656000000.0,4993000000.0,4646000000.0,4374000000.0,3914000000.0
Pretax Income,26526000000.0,27284000000.0,24727000000.0,22673000000.0,20339000000.0
Other Income Expense,-331000000.0,-252000000.0,50000000.0,69000000.0,-270000000.0
Other Non Operating Income Expenses,-169000000.0,-137000000.0,-61000000.0,-93000000.0,-38000000.0
Special Income Charges,-161000000.0,NaN,NaN,NaN,-4000000.0
Write Off,161000000.0,NaN,NaN,NaN,4000000.0
Gain On Sale Of Security,-1000000.0,-115000000.0,141000000.0,162000000.0,-228000000.0
Net Non Operating Interest Income Expense,-175000000.0,641000000.0,423000000.0,252000000.0,210000000.0
Interest Expense Non Operating,909000000.0,525000000.0,482000000.0,496000000.0,490000000.0
Interest Income Non Operating,734000000.0,1166000000.0,905000000.0,748000000.0,700000000.0
Operating Income,27032000000.0,26895000000.0,24254000000.0,22352000000.0,20399000000.0
Operating Expense,15365000000.0,13320000000.0,15140000000.0,14377000000.0,14860000000.0
Research And Development,7142000000.0,6659000000.0,6739000000.0,6984000000.0,6844000000.0
Selling General And Administration,8223000000.0,6661000000.0,8401000000.0,7393000000.0,8016000000.0
Selling And Marketing Expense,6246000000.0,5187000000.0,6204000000.0,5750000000.0,5679000000.0
General And Administrative Expense,1977000000.0,1474000000.0,2197000000.0,1643000000.0,2337000000.0
Other Gand A,1977000000.0,1474000000.0,2197000000.0,1643000000.0,2337000000.0
Gross Profit,42397000000.0,40215000000.0,39394000000.0,36729000000.0,35259000000.0
Cost Of Revenue,19623000000.0,16302000000.0,16795000000.0,16128000000.0,17488000000.0
Total Revenue,62020000000.0,56517000000.0,56189000000.0,52857000000.0,52747000000.0
Operating Revenue,62020000000.0,56517000000.0,56189000000.0,52857000000.0,52747000000.0

In [16]:
dt = "2023-12-31"
df_income_2023q4 = df_income.loc[:, dt]
df_income_2023q4

Tax Effect Of Unusual Items                                     -29160000.0
Tax Rate For Calcs                                                     0.18
Normalized EBITDA                                             33556000000.0
Total Unusual Items                                            -162000000.0
Total Unusual Items Excluding Goodwill                         -162000000.0
Net Income From Continuing Operation Net Minority Interest    21870000000.0
Reconciled Depreciation                                        5959000000.0
Reconciled Cost Of Revenue                                    19623000000.0
EBITDA                                                        33394000000.0
EBIT                                                          27435000000.0
Net Interest Income                                            -175000000.0
Interest Expense                                                909000000.0
Interest Income                                                 734000000.0
Normalized Income                                             22002840000.0
Net Income From Continuing And Discontinued Operation         21870000000.0
Total Expenses                                                34988000000.0
Total Operating Income As Reported                            27032000000.0
Diluted Average Shares                                         7468000000.0
Basic Average Shares                                           7432000000.0
Diluted EPS                                                            2.93
Basic EPS                                                              2.94
Diluted NI Availto Com Stockholders                           21870000000.0
Net Income Common Stockholders                                21870000000.0
Net Income                                                    21870000000.0
Net Income Including Noncontrolling Interests                 21870000000.0
Net Income Continuous Operations                              21870000000.0
Tax Provision                                                  4656000000.0
Pretax Income                                                 26526000000.0
Other Income Expense                                           -331000000.0
Other Non Operating Income Expenses                            -169000000.0
Special Income Charges                                         -161000000.0
Write Off                                                       161000000.0
Gain On Sale Of Security                                         -1000000.0
Net Non Operating Interest Income Expense                      -175000000.0
Interest Expense Non Operating                                  909000000.0
Interest Income Non Operating                                   734000000.0
Operating Income                                              27032000000.0
Operating Expense                                             15365000000.0
Research And Development                                       7142000000.0
Selling General And Administration                             8223000000.0
Selling And Marketing Expense                                  6246000000.0
General And Administrative Expense                             1977000000.0
Other Gand A                                                   1977000000.0
Gross Profit                                                  42397000000.0
Cost Of Revenue                                               19623000000.0
Total Revenue                                                 62020000000.0
Operating Revenue                                             62020000000.0
Name: 2023-12-31 00:00:00, dtype: object

In [ ]:
income_col = ['Total Operating Income As Reported']

In [3]:
# - balance sheet
# msft.balance_sheet
msft.quarterly_balance_sheet

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Ordinary Shares Number,7432262329.0,7431000000.0,7432000000.0,7437000000.0,7447000000.0
Share Issued,7432262329.0,7431000000.0,7432000000.0,7437000000.0,7447000000.0
Net Debt,56914000000.0,NaN,12533000000.0,21648000000.0,32470000000.0
Total Debt,88374000000.0,84989000000.0,59965000000.0,60522000000.0,60114000000.0
Tangible Book Value,89441000000.0,144029000000.0,128971000000.0,116864000000.0,104876000000.0
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,80982000000.0,143945000000.0,111256000000.0,104419000000.0,99495000000.0
Other Short Term Investments,63677000000.0,63493000000.0,76552000000.0,77857000000.0,83849000000.0
Cash And Cash Equivalents,17305000000.0,80452000000.0,34704000000.0,26562000000.0,15646000000.0
Cash Equivalents,7769000000.0,73074000000.0,26226000000.0,18053000000.0,8342000000.0
Cash Financial,9536000000.0,7378000000.0,8478000000.0,8509000000.0,7304000000.0

In [4]:
# - cash flow statement
# msft.cashflow
msft.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Free Cash Flow,9118000000.0,20666000000.0,19827000000.0,17834000000.0,4899000000.0
Repurchase Of Capital Stock,-4000000000.0,-4831000000.0,-5704000000.0,-5509000000.0,-5459000000.0
Repayment Of Debt,-2916000000.0,-1500000000.0,-1000000000.0,0.0,-750000000.0
Issuance Of Debt,10773000000.0,25765000000.0,NaN,NaN,0.0
Issuance Of Capital Stock,261000000.0,685000000.0,512000000.0,536000000.0,243000000.0
Capital Expenditure,-9735000000.0,-9917000000.0,-8943000000.0,-6607000000.0,-6274000000.0
End Cash Position,17305000000.0,80452000000.0,34704000000.0,26562000000.0,15646000000.0
Beginning Cash Position,80452000000.0,34704000000.0,26562000000.0,15646000000.0,22884000000.0
Effect Of Exchange Rate Changes,72000000.0,-99000000.0,-81000000.0,29000000.0,88000000.0
Changes In Cash,-63219000000.0,45847000000.0,8223000000.0,10887000000.0,-7326000000.0
Financing Cash Flow,-10147000000.0,14761000000.0,-11413000000.0,-10290000000.0,-11349000000.0
Cash Flow From Continuing Financing Activities,-10147000000.0,14761000000.0,-11413000000.0,-10290000000.0,-11349000000.0
Net Other Financing Charges,-201000000.0,-307000000.0,-167000000.0,-258000000.0,-317000000.0
Cash Dividends Paid,-5574000000.0,-5051000000.0,-5054000000.0,-5059000000.0,-5066000000.0
Common Stock Dividend Paid,-5574000000.0,-5051000000.0,-5054000000.0,-5059000000.0,-5066000000.0
Net Common Stock Issuance,-3739000000.0,-4146000000.0,-5192000000.0,-4973000000.0,-5216000000.0
Common Stock Payments,-4000000000.0,-4831000000.0,-5704000000.0,-5509000000.0,-5459000000.0
Common Stock Issuance,261000000.0,685000000.0,512000000.0,536000000.0,243000000.0
Net Issuance Payments Of Debt,-633000000.0,24265000000.0,-1000000000.0,0.0,-750000000.0
Net Short Term Debt Issuance,-8490000000.0,18692000000.0,NaN,NaN,0.0
Short Term Debt Issuance,NaN,18692000000.0,NaN,NaN,NaN
Net Long Term Debt Issuance,7857000000.0,5573000000.0,-1000000000.0,0.0,-750000000.0
Long Term Debt Payments,-2916000000.0,-1500000000.0,-1000000000.0,0.0,-750000000.0
Long Term Debt Issuance,10773000000.0,7073000000.0,NaN,NaN,0.0
Investing Cash Flow,-71925000000.0,503000000.0,-9134000000.0,-3264000000.0,-7150000000.0
Cash Flow From Continuing Investing Activities,-71925000000.0,503000000.0,-9134000000.0,-3264000000.0,-7150000000.0
Net Other Investing Changes,1347000000.0,-982000000.0,-269000000.0,-1686000000.0,-301000000.0
Net Investment Purchase And Sale,1492000000.0,12588000000.0,419000000.0,5330000000.0,104000000.0
Sale Of Investment,5750000000.0,21048000000.0,12395000000.0,14393000000.0,11703000000.0
Purchase Of Investment,-4258000000.0,-8460000000.0,-11976000000.0,-9063000000.0,-11599000000.0
Net Business Purchase And Sale,-65029000000.0,-1186000000.0,-341000000.0,-301000000.0,-679000000.0
Purchase Of Business,-65029000000.0,-1186000000.0,-341000000.0,-301000000.0,-679000000.0
Net PPE Purchase And Sale,-9735000000.0,-9917000000.0,-8943000000.0,-6607000000.0,-6274000000.0
Purchase Of PPE,-9735000000.0,-9917000000.0,-8943000000.0,-6607000000.0,-6274000000.0
Operating Cash Flow,18853000000.0,30583000000.0,28770000000.0,24441000000.0,11173000000.0
Cash Flow From Continuing Operating Activities,18853000000.0,30583000000.0,28770000000.0,24441000000.0,11173000000.0
Change In Working Capital,-10300000000.0,2418000000.0,4243000000.0,1843000000.0,-10347000000.0
Change In Other Working Capital,-7092000000.0,-2701000000.0,14905000000.0,1233000000.0,-8049000000.0
Change In Other Current Liabilities,1492000000.0,-3815000000.0,2864000000.0,1721000000.0,2076000000.0
Change In Other Current Assets,-702000000.0,-2809000000.0,-3967000000.0,598000000.0,-457000000.0
Change In Payables And Accrued Expense,-2521000000.0,1214000000.0,1311000000.0,-407000000.0,-2058000000.0
Change In Payable,-2521000000.0,1214000000.0,1311000000.0,-407000000.0,-2058000000.0
Change In Account Payable,-2521000000.0,1214000000.0,1311000000.0,-407000000.0,-2058000000.0
Change In Inventory,1474000000.0,-505000000.0,374000000.0,106000000.0,1305000000.0
Change In Receivables,-2951000000.0,11034000000.0,-11244000000.0,-1408000000.0,-3164000000.0
Changes In Account Receivables,-2951000000.0,11034000000.0,-11244000000.0,-1408000000.0,-3164000000.0
Stock Based Compensation,2828000000.0,2507000000.0,2416000000.0,2465000000.0,2538000000.0
Deferred Tax,-1702000000.0,-568000000.0,-1888000000.0,-1675000000.0,-1305000000.0
Deferred Income Tax,-1702000000.0,-568000000.0,-1888000000.0,-1675000000.0,-1305000000.0
Depreciation Amortization Depletion,5959000000.0,3921000000.0,3874000000.0,3549000000.0,3648000000.0
Depreciation And Amortization,5959000000.0,3921000000.0,3874000000.0,3549000000.0,3648000000.0
Depreciation,5959000000.0,NaN,3874000000.0,3549000000.0,3648000000.0
Operating Gains Losses,198000000.0,14000000.0,44000000.0,-40000000.0,214000000.0
Net Income From Continuing Operations,21870000000.0,22291000000.0,20081000000.0,18299000000.0,16425000000.0

In [5]:
spy = yf.Ticker("SPY")

# get all stock info
spy.info

{'longBusinessSummary': 'The Trust seeks to achieve its investment objective by holding a portfolio of the common stocks that are included in the index (the “Portfolio”), with the weight of each stock in the Portfolio substantially corresponding to the weight of such stock in the index.',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 509.75,
 'open': 513.14,
 'dayLow': 509.8053,
 'dayHigh': 515.89,
 'regularMarketPreviousClose': 509.75,
 'regularMarketOpen': 513.14,
 'regularMarketDayLow': 509.8053,
 'regularMarketDayHigh': 515.89,
 'trailingPE': 25.933285,
 'volume': 58302422,
 'regularMarketVolume': 58302422,
 'averageVolume': 77195325,
 'averageVolume10days': 64524010,
 'averageDailyVolume10Day': 64524010,
 'bid': 514.71,
 'ask': 514.91,
 'bidSize': 800,
 'askSize': 800,
 'yield': 0.012999999,
 'totalAssets': 503321591808,
 'fiftyTwoWeekLow': 380.65,
 'fiftyTwoWeekHigh': 515.89,
 'fiftyDayAverage': 489.487,
 'twoHundredDayAverage': 453.1195,
 'trailingAnnualDividendRate': 5.662,
 'trailingAnnualDividendYield': 0.011107406,
 'navPrice': 509.73602,
 'currency': 'USD',
 'category': 'Large Blend',
 'ytdReturn': 0.072458,
 'beta3Year': 1.0,
 'fundFamily': 'SPDR State Street Global Advisors',
 'fundInceptionDate': 727660800,
 'legalType': 'Exchange Traded Fund',
 'threeYearAverageReturn': 0.115884304,
 'fiveYearAverageReturn': 0.1482072,
 'exchange': 'PCX',
 'quoteType': 'ETF',
 'symbol': 'SPY',
 'underlyingSymbol': 'SPY',
 'shortName': 'SPDR S&P 500',
 'longName': 'SPDR S&P 500 ETF Trust',
 'firstTradeDateEpochUtc': 728317800,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': 'e97de790-7e95-3762-8917-c59fcab3735e',
 'messageBoardId': 'finmb_6160262',
 'gmtOffSetMilliseconds': -18000000,
 'trailingPegRatio': None}